SaffronCity_MrPsychicsHouse_Text_YouWantedThis:: @ 819C142
    .string "…Wait! Don't say a word!\p"
    .string "You wanted this!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic:: @ 819C16C
    .string "{PLAYER} received TM56\n"
    .string "from Mr. Psychic.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29:: @ 819C18F
    .string "You already know, don't you?\n"
    .string "TM56 is Extrasensory.\p"
    .string "Huh? TM29?\n"
    .string "No, no, you want TM56, trust me.\l"
	.string "I know your mind better than you.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom:: @ 819C1FC
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"

