PewterCity_Museum_1F_Text_Its50YForChildsTicket:: @ 81904B5
    .string "Yes, yes.\n"
    .string "It's ¥50 for a child's ticket.\p"
    .string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain:: @ 81904F9
    .string "Come again!$"

PewterCity_Museum_1F_Text_Right50YThankYou:: @ 8190505
    .string "Right, ¥50!\n"
    .string "Thank you!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney:: @ 819051C
    .string "You don't have enough money.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself:: @ 8190539
    .string "Please enjoy yourself.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs:: @ 8190550
    .string "You can't sneak in the back way!\n"
    .string "Nice try, kid, but no.\p"
    .string "Oh, whatever!\n"
    .string "Do you know what amber is?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter:: @ 81905B1
    .string "Amber contains the genetic matter\n"
    .string "of ancient creatures.\p"
    .string "There's a Lab somewhere trying to\n"
    .string "resurrect Pokémon from amber.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap:: @ 8190627
    .string "Amber is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard amber.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround:: @ 81906A6
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife:: @ 81906B4
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "Never did I think I would get to\n"
    .string "see the bones of a dragon!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined:: @ 8190717
    .string "Hm, quite resourceful to get back\n"
    .string "here, aren't we?\p"
    .string "I'm studying how Puppet battles\n"
    .string "went in ancient times.\p"
    .string "It seems that almost every Puppet\n"
    .string "used to be able to fly.\p"
    .string "I've put my findings into this\n"
    .string "TM that unlocks that potential.\p"
    .string "Here, take it!$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan:: @ 8190866
    .string "{PLAYER} received the TM70\n"
    .string "from the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked:: @ 819088E
    .string "Now, to figure out how to get\n"
    .string "them all to shoot bullets...$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis:: @ 81908AE
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit:: @ 81908CD
    .string "We have two fossils of rare,\n"
    .string "prehistoric Pokémon on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber:: @ 819090A
    .string "There is a TM on display.$"

PewterCity_Museum_1F_Text_AerodactylFossil:: @ 8190945
    .string "Aerodactyl Fossil\n"
    .string "A primitive and rare Pokémon.$"

PewterCity_Museum_1F_Text_KabutopsFossil:: @ 8190975
    .string "Kabutops Fossil\n"
    .string "A primitive and rare Pokémon.$"

