SafariZone_SecretHouse_Text_CongratsYouveWon:: @ 8177DC1
    .string "Ah! Finally!\p"
    .string "You're the first person to reach\n"
    .string "the Secret House!\p"
    .string "Although I made a campaign\n"
    .string "for our grand opening,\p"
    .string "I was getting worried that no one\n"
    .string "would win our campaign prize.\p"
    .string "Congratulations!\n"
    .string "You have won!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant:: @ 8177E92
    .string "{PLAYER} received HM07\n"
    .string "from the attendant!$"

SafariZone_SecretHouse_Text_ExplainSurf:: @ 8177EB7
    .string "HM07 is Waterfall.\p"
    .string "You can use it while surfing to\n"
    .string "scale waterfalls.\p"
    .string "It, uh, might not be too useful\n"
    .string "if you don't have the Surf HM...\p"
	.string "It's also a good move for battles,\n"
	.string "especially on Water-type puppets.\p"
    .string "You're super lucky for winning this\n"
    .string "fabulous prize!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize:: @ 8177F72
    .string "You don't have room for this\n"
    .string "fabulous prize!$"

