CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons:: @ 819A015
    .string "EEVEE can evolve into one of three\n"
    .string "kinds of POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail:: @ 819A04A
    .string "There's an e-mail message.\p"
    .string "… … …\p"
    .string "There are three legendary X\n"
    .string "Puppets.\p"
    .string "They are Utsuho, Suwako, and\n"
    .string "Tenshi.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to Cerulean.\p"
    .string "From: PUPPET RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe:: @ 819A128
    .string "An amber pipe!$"

Text_MetronomeTeach:: @ 819A137
    .string "Tch-tch-tch!\n"
    .string "I'll teach you a nifty move.\p"
    .string "Teach it to a Puppet, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called Metronome.\n"
    .string "Does it strike your fancy?$"

Text_MetronomeDeclined:: @ 819A1CB
    .string "I tell you, it's a lot of fun!$"

Text_MetronomeWhichMon:: @ 819A1EA
    .string "Okay!\n"
    .string "Which POKéMON should I teach?$"

Text_MetronomeTaught:: @ 819A20E
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a Metronome.\p"
    .string "It tweaks your Puppet's brain into\n"
    .string "using moves it doesn't even know.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_GotTM69::
    .string "{PLAYER} received the TM69\n"
    .string "from the man.$"
