SaffronCity_Dojo_Text_MasterKoichiIntro:: @ 819B12C
	.string "Behold!\n"
	.string "It is I, the Karate King!\p"
	.string "Huh?\n"
	.string "I don't look like one?\p"
	.string "Why, you! Can't you see the\n"
	.string "black belt I'm wearing?\p"
	.string "Anyway...\p"
	.string "Hee-ho!\n"
	.string "Prepare yourself!$"
	
    .string "Grunt!\p"
    .string "I am the KARATE MASTER!\n"
    .string "I am the LEADER here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Oof! Ouch! Owie!\n"
    .string "Beaten!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon:: @ 819B1A7
	.string "Well, I don't have any badges\n"
	.string "for you, sorry.\p"
	.string "For some reason, the Puppetry League\n"
	.string "didn't like the Imakuni?Badge.\p"
	.string "So uhh, take one of these weird\n"
	.string "Pokémon sitting in the back there.$"

    .string "Indeed, I have lost!\p"
    .string "But, I beseech you, do not take\n"
    .string "our emblem as your trophy!\p"
    .string "In return, I will give you a prized\n"
    .string "FIGHTING POKéMON!\p"
    .string "Choose whichever one you like!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs:: @ 819B24C
    .string "You know, at first I thought\n"
    .string "the sign said “Karaoke Dojo”...$"

SaffronCity_Dojo_Text_MikeIntro:: @ 819B275
    .string "Hoargh!\n"
    .string "Take your shoes off!$"

SaffronCity_Dojo_Text_MikeDefeat:: @ 819B292
    .string "I give up!$"

SaffronCity_Dojo_Text_MikePostBattle:: @ 819B29D
    .string "You wait 'til you see our Master!\n"
    .string "I'm a small fry compared to him!$"

SaffronCity_Dojo_Text_HidekiIntro:: @ 819B2E0
    .string "One fight or a hundred!\n"
    .string "We're always ready!$"

SaffronCity_Dojo_Text_HidekiDefeat:: @ 819B2FD
    .string "Judge!\n"
    .string "One point!$"

SaffronCity_Dojo_Text_HidekiPostBattle:: @ 819B30F
    .string "Our Master is a pro fighter.\n"
    .string "Be prepared to lose!$"

SaffronCity_Dojo_Text_AaronIntro:: @ 819B341
    .string "Hiyah!\n"
    .string "I have no fear for anything tough!\p"
    .string "I shatter boulders for training\n"
    .string "every day!$"

SaffronCity_Dojo_Text_AaronDefeat:: @ 819B396
    .string "Yow!\n"
    .string "Stubbed fingers!$"

SaffronCity_Dojo_Text_AaronPostBattle:: @ 819B3AC
    .string "The only thing that frightens us is\n"
    .string "psychic power!$"

SaffronCity_Dojo_Text_HitoshiIntro:: @ 819B3DF
    .string "Hwaah!\p"
    .string "You're trespassing in our\n"
    .string "Fighting Dojo!$"

SaffronCity_Dojo_Text_HitoshiDefeat:: @ 819B40F
    .string "Oof!\n"
    .string "I give up!$"

SaffronCity_Dojo_Text_HitoshiPostBattle:: @ 819B41F
    .string "The prime fighters across the land\n"
    .string "train here.$"

SaffronCity_Dojo_Text_YouWantHitmonlee:: @ 819B44E
    .string "You want the hard-hitting\n"
    .string "and unflinching CSendai?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster:: @ 819B473
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the alleged Karate Master.$"

SaffronCity_Dojo_Text_YouWantHitmonchan:: @ 819B49E
    .string "You want the cunning\n"
    .string "and resilient CTenma?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2:: @ 819B4C7
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy:: @ 819B4E1
    .string "Better not get greedy…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide:: @ 819B4F8
    .string "Enemies on every side!$"

SaffronCity_Dojo_Text_GoesAroundComesAround:: @ 819B50F
    .string "What goes around comes around.$"

SaffronCity_Dojo_Text_FightingDojo:: @ 819B52E
    .string "FIGHTING DOJO$"

