Text_MayIHelpYou:: @ 81A6211
	.string "Hi, there!\n"
	.string "May I help you?$"

Text_FillOutQuestionnaire:: @ 81A622C
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Text_QuestionnaireThankYou:: @ 81A6265
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Text_YouKnowThoseWords::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must be looking\n"
	.string "for this.$"

Text_YouKnowThoseWordsTutor::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must be looking\n"
	.string "for some help.\p"
	.string "From now on, Puppets can learn\n"
	.string "moves from the Move Tutor even\l"
	.string "if no other Puppet knows the move.\p"
	.string "How lucky for you!$"

Text_YouKnowThoseWordsTutorRedundant::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must be looking\n"
	.string "for some help.\p"
	.string "But, I can't actually help you\n"
	.string "with this.\p"
	.string "You can already tutor any move\n"
	.string "to any Puppet.$"

Text_YouKnowThoseWordsGaugeRedundant::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must be looking\n"
	.string "for this.\p"
	.string "Wait, you already have an\n"
	.string "Effort Gauge.$"

Text_YouKnowThoseWordsFight::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must be looking\n"
	.string "for a fight.$"

Text_CheatPostFightImakuni::
	.string "Hey, what gives!\n"
	.string "Stop beating me up!$"

Text_CheatPostFightChampion::
	.string "... ...\n"
	.string "... ...$"
	

Text_Got100Nuggets::
    .string "{PLAYER} received 100 Nuggets.$"

Text_Got600RareCandy::
    .string "{PLAYER} received 250 Rare Candies.$"

Text_GotAllTMs::
    .string "{PLAYER} received a full set of TMs.$"

Text_GotEffortGauge::
    .string "{PLAYER} received the Effort Gauge.$"

Text_GotCMaribel::
    .string "{PLAYER} obtained a CMaribel!$"

Text_GotCRenko::
    .string "{PLAYER} obtained a CRenko!$"

Text_YouCanAccessMysteryGift:: @ 81A6359
	.string "Once you save your game, you can\n"
	.string "access the Mystery Gift.$"

Text_ThankYouForAccessingMysteryGift:: @ 81A6393
	.string "Thank you for accessing the\n"
	.string "Mystery Gift System.$"
