Route2_EastBuilding_Text_GiveHM05IfSeen10Mons:: @ 819D64F
    .string "Hi! Remember me?\n"
    .string "I'm one of Prof. Oak's Aides.\p"
    .string "If your Tohodex has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "Prof. Oak entrusted me with\n"
    .string "HM05 for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of Puppet?$"

Route2_EastBuilding_Text_GreatHereYouGo:: @ 819D74E
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of Puppet!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide:: @ 819D7A1
    .string "{PLAYER} received HM05\n"
    .string "from the Aide.$"

Route2_EastBuilding_Text_ExplainHM05:: @ 819D7C1
    .string "HM05 contains the hidden move\n"
    .string "Flash.\p"
    .string "Flash isn't actually used on the\n"
    .string "field, unlike most HMs, but it's\p$"
	.string "still a decent attack.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel:: @ 819D81E
    .string "I hear you don't need Flash anymore\n"
    .string "to get through Rock Tunnel.$"

