Route12_Text_MonSprawledOutInSlumber:: @ 8185317
    .string "A pink blob is blocking the way.\n"
    .string "It feels weird to touch...$"

Text_SnorlaxWokeUp:: @ 8185354
    .string "CDoremy woke up!\p"
    .string "It attacked in a grumpy rage!$"

Text_SnorlaxReturnedToMountains:: @ 8185383
    .string "CDoremy calmed down.\n"
    .string "It gave a huge yawn…\l"
    .string "And returned to the mountains.$"

Text_WantToUsePokeFlute:: @ 81853CC
    .string "Want to use the Merlin Flute?$"

Text_PlayedPokeFlute:: @ 81853E8
    .string "{PLAYER} played the Merlin Flute.$"

Route12_Text_NedIntro:: @ 8185402
    .string "Yeah!\n"
    .string "I got a bite here!$"

Route12_Text_NedDefeat:: @ 818541B
    .string "Tch!\n"
    .string "Just a small fry…$"

Route12_Text_NedPostBattle:: @ 8185432
    .string "Hang on!\n"
    .string "My line's snagged!$"

Route12_Text_ChipIntro:: @ 818544E
    .string "Be patient.\n"
    .string "Fishing is a waiting game.$"

Route12_Text_ChipDefeat:: @ 8185475
    .string "That one got away!$"

Route12_Text_ChipPostBattle:: @ 8185488
    .string "With a better Rod, I could catch\n"
    .string "better Puppets…$"

Route12_Text_JustinIntro:: @ 81854B9
    .string "I'm searching for a Dubious Tome.\n"
    .string "Have you found one?$"

Route12_Text_JustinDefeat:: @ 81854ED
    .string "Oww!$"

Route12_Text_JustinPostBattle:: @ 81854F2
    .string "I could have made my Puppet\n"
    .string "evolve with a Dubious Tome.\p"
    .string "I would have won then, I bet.$"

Route12_Text_LucaIntro:: @ 8185547
    .string "Electricity is my specialty.\p"
    .string "I don't know a thing about Puppets\n"
    .string "of the sea, though.$"

Route12_Text_LucaDefeat:: @ 818559B
    .string "Unplugged!$"

Route12_Text_LucaPostBattle:: @ 81855A6
    .string "Water conducts electricity, so you\n"
    .string "should zap sea Puppets.$"

Route12_Text_HankIntro:: @ 81855E1
    .string "The Fishing Fool versus Puppet\n"
    .string "Kid!$"

Route12_Text_HankDefeat:: @ 8185606
    .string "Touch too much!$"

Route12_Text_HankPostBattle:: @ 8185616
    .string "I guess you get to be good at\n"
    .string "what you like.\p"
    .string "Well, you beat me at Puppets,\n"
    .string "but you can't top me at fishing.$"

Route12_Text_ElliotIntro:: @ 8185682
    .string "I love fishing, don't get me wrong.\p"
    .string "But it'd be best if I also had more\n"
    .string "work.$"

Route12_Text_ElliotDefeat:: @ 81856D0
    .string "It's not easy…$"

Route12_Text_ElliotPostBattle:: @ 81856DF
    .string "It's all right.\n"
    .string "Losing doesn't bug me anymore.$"

Route12_Text_AndrewIntro:: @ 818570E
    .string "What's catching?\p"
    .string "You never know what you could\n"
    .string "catch!$"

Route12_Text_AndrewDefeat:: @ 8185744
    .string "Lost it!$"

Route12_Text_AndrewPostBattle:: @ 818574D
    .string "What, Hina?\p"
    .string "I catch them all the time, sure.\n"
    .string "But, boy are they wimpy.$"

Route12_Text_RouteSign:: @ 8185797
    .string "ROUTE 12 \n"
    .string "North to LAVENDER$"

Route12_Text_SportfishingArea:: @ 81857B3
    .string "SPORTFISHING AREA$"

Route12_Text_JesIntro:: @ 81857C5
    .string "JES: If I win, I'm going to\n"
    .string "propose to GIA.$"

Route12_Text_JesDefeat:: @ 81857F1
    .string "JES: Oh, please, why couldn't you\n"
    .string "let us win?$"

Route12_Text_JesPostBattle:: @ 818581F
    .string "JES: Oh, GIA, forgive me,\n"
    .string "my love!$"

Route12_Text_JesNotEnoughMons:: @ 8185842
    .string "JES: GIA and I, we'll be\n"
    .string "together forever.\p"
    .string "We won't battle unless you have\n"
    .string "two POKéMON of your own.$"

Route12_Text_GiaIntro:: @ 81858A6
    .string "GIA: Hey, JES…\p"
    .string "If we win, I'll marry you!$"

Route12_Text_GiaDefeat:: @ 81858D0
    .string "GIA: Oh, but why?$"

Route12_Text_GiaPostBattle:: @ 81858E2
    .string "GIA: JES, you silly!\n"
    .string "You ruined this!$"

Route12_Text_GiaNotEnoughMons:: @ 8185908
    .string "GIA: I can't bear to battle\n"
    .string "without my JES!\p"
    .string "Don't you have one more POKéMON?$"

Route12_Text_Koga::
	.string "It seems the Doremy that settled\n"
	.string "north of here took out the bridge.\p"
	.string "I've been helping with the\n"
	.string "reconstruction efforts here.\p"
	.string "Hm?\n"
	.string "You're looking for Koga?\p"
	.string "Ah. That would be me.\p"
	.string "The work is finished, so I will\n"
	.string "be returning to Fuchsia City's Gym.\p"
	.string "As a token of apology for\n"
	.string "my absence, please take this.$"

Route12_Text_Koga2::
	.string "If you seek to battle me for the\n"
	.string "MarshBadge, come to Fuchsia City Gym.$"

Route12_Text_ConstructionGuy::
	.string "Bridge's out.\n"
	.string "Come by later.\p"
	.string "If you need to go to Fuchsia,\n"
	.string "try heading west from Celadon.$"
