VermilionCity_Mart_Text_TeamRocketAreWickedPeople:: @ 8194A77
    .string "There are wicked people who will\n"
    .string "use Puppets for criminal acts.\p"
    .string "Team Rocket traffics in rare\n"
    .string "Puppets, for example.\p"
    .string "They also abandon Puppets that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, Team Rocket.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer:: @ 8194B65
    .string "I think Puppets can be good or\n"
    .string "bad. It depends on the Trainer.$"

