SafariZone_West_Text_KogaPatrolsSafariEverySoOften:: @ 8177C47
    .string "The Safari Zone's huge, wouldn't\n"
    .string "you say?\p"
    .string "Fuchsia's Gym Leader, Koga, \n"
    .string "patrols the grounds every so often.\p"
    .string "Thanks to him, we can play here\n"
    .string "knowing that we're safe.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch:: @ 8177CEB
    .string "Tossing rocks at Puppets is just\n"
    .string "mean. Who would do that?$"

SafariZone_West_Text_BaitMakesMonStickAround:: @ 8177D39
    .string "Using Bait will make Puppets more\n"
    .string "likely to stick around, but why not\l"
    .string "just throw Orbs at them?$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted:: @ 8177D8B
    .string "I hiked a lot, but I didn't see any\n"
    .string "Puppets I wanted.$"

