SilphCo_1F_Text_WelcomePresidentInBoardroom:: @ 81754F7
    .string "Welcome.\p"
    .string "The President is in the boardroom\n"
    .string "on 11F.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile:: @ 817552A
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign:: @ 8175549
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

SilphCo_1F_Text_Mamizou::
	.string "Yo.\n"
	.string "Headed up?\p"
	.string "Check the south-east corner of\n"
	.string "the 5th floor for a card key.\p"
	.string "Then, take that to the 3rd floor\n"
	.string "to find the way to the Boss.\p"
	.string "The strongest Rockets are on the\n"
	.string "highest floors, so watch yourself.$"

