PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow:: @ 81917E4
    .string "Puppets learn new techniques as\n"
    .string "they grow.\p"
    .string "But some moves must be taught to\n"
    .string "them by people.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused:: @ 8191840
    .string "A Puppet becomes easier to \n"
    .string "catch if it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But catching Puppets is never\n"
    .string "a sure thing!$"

