FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon:: @ 8198CB7
    .string "You can't become a good Trainer\n"
    .string "with just one strong Puppet.\p"
    .string "But raising many Puppets evenly\n"
    .string "is no easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian:: @ 8198D2E
    .string "There's a narrow trail west of\n"
    .string "Viridian City.\p"
    .string "It goes to the Puppetry League HQ.\n"
    .string "The HQ governs all Trainers.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex:: @ 8198D9B
    .string "If you're working on a Tohodex,\n"
    .string "visit the Safari Zone.\p"
    .string "All sorts of rare Puppets gather\n"
    .string "there.$"

