CeruleanCity_House1_Text_BadgesHaveAmazingSecrets:: @ 81918E7
    .string "Only skilled Trainers can collect\n"
    .string "Puppet Badges.\p"
    .string "I see you have at least one.\p"
    .string "Those Badges have amazing secrets,\n"
    .string "did you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge:: @ 8191967
    .string "Now then…\p"
    .string "Which of the eight Badges should\n"
    .string "I describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime:: @ 819199E
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash:: @ 81919BE
    .string "It lets you use the move\n"
    .string "Flash outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut:: @ 8191A31
    .string "Puppets up to Lv. 40 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "Puppets of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "Cut outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly:: @ 8191AF9
    .string "It lets you use the move\n"
    .string "Fly outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength:: @ 8191B69
    .string "Puppets up to Lv. 60 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "Puppets of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "Strength outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf:: @ 8191C36
    .string "It lets you use the move\n"
    .string "Surf outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash:: @ 8191CA9
    .string "Puppets up to Lv. 80 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "Puppets of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "Rock Smash outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall:: @ 8191D78
    .string "It also lets you use the move\n"
    .string "Waterfall outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou:: @ 8191DF8
    .string "All Puppets will obey you!$"

