ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC:: @ 8190384
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown:: @ 81903E5
    .string "There's a Puppet Center in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing Puppets.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons:: @ 8190450
    .string "Puppet Centers heal your tired,\n"
    .string "hurt, or fainted Puppets.\p"
    .string "They make all Puppets completely\n"
    .string "healthy.$"

GlobalMoveTutor_Text_Intro::
	.string "I can teach your Puppets moves.\n"
	.string "What would you like?$"

GlobalMoveTutor_Text_Egg::
	.string "That's an Egg.\n"
	.string "Not much I can teach it.$"

GlobalMoveTutor_Text_NothingToLearn::
	.string "There's nothing I can teach\n"
	.string "this Puppet. Sorry.$"

GlobalMoveTutor_Text_NothingToForget::
	.string "This Puppet can't forget the\n"
	.string "last move it knows.$"

GlobalMoveTutor_Text_RelearnWhich::
	.string "Which Puppet wants to learn\n"
	.string "a move it used to know?$"

GlobalMoveTutor_Text_TutorWhich::
	.string "Which Puppet wants to learn\n"
	.string "from another Puppet?$"
