SevenIsland_Mart_MapScripts:: @ 8170B30
	.byte 0

SevenIsland_Mart_EventScript_Clerk:: @ 8170B31
	goto_if_questlog EventScript_ReleaseEnd
	lock
	faceplayer
	goto EventScript_ScaledShop

SevenIsland_Mart_EventScript_Lass:: @ 8170B6E
	msgbox SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn, MSGBOX_NPC
	end

SevenIsland_Mart_EventScript_Hiker:: @ 8170B77
	msgbox SevenIsland_Mart_Text_PreparationsCompleteForRuins, MSGBOX_NPC
	end

SevenIsland_Mart_EventScript_Fisher:: @ 8170B80
	msgbox SevenIsland_Mart_Text_NeedToFishOnSevenIsland, MSGBOX_NPC
	end
