SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn:: @ 81A0A4F
    .string "Puppets have personalities of their\n"
    .string "own, just like people.\p"
    .string "My Reimu has a Hasty nature,\n"
    .string "so it grew to be a speedy Puppet.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins:: @ 81A0ACC
    .string "Okay, preparations are complete\n"
    .string "for me to explore the Ruins.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland:: @ 81A0B09
    .string "I need to fish on Seven Island.\p"
    .string "That will complete my fishing tour\n"
    .string "of the Sevii Islands.\p"
    .string "I'd better stock up on some\n"
    .string "Toho Orbs first, though.$"

