MtMoon_B2F_Text_MiguelIntro:: @ 8172B64
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat:: @ 8172B99
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil:: @ 8172BAB
    .string "We'll each take a fossil!\n"
    .string "No being greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine:: @ 8172BD6
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils:: @ 8172BFB
    .string "Far away, on CINNABAR ISLAND,\n"
    .string "there's a POKéMON LAB.\p"
    .string "They do research on regenerating\n"
    .string "fossils.$"

MtMoon_B2F_Text_Grunt1Intro:: @ 8172C5A
    .string "We, TEAM ROCKET, shall find the\n"
    .string "fossils!\p"
    .string "Reviving POKéMON from them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat:: @ 8172CB8
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle:: @ 8172CCB
    .string "You made me mad!\n"
    .string "TEAM ROCKET will blacklist you!$"

MtMoon_B2F_Text_Grunt2Intro:: @ 8172CFC
    .string "We, TEAM ROCKET, are POKéMON\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat:: @ 8172D46
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle:: @ 8172D51
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_Grunt3Intro:: @ 8172D82
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_Grunt3Defeat:: @ 8172DAF
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle:: @ 8172DC1
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_B2F_Text_Grunt4Intro:: @ 8172DF0
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat:: @ 8172E3E
    .string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle:: @ 8172E4B
    .string "POKéMON lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil:: @ 8172E77
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil:: @ 8172E94
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil:: @ 8172EB2
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil:: @ 8172ECD
    .string "Obtained the DOME FOSSIL!$"

MtMoon_B2F_Text_ImakuniIntro::
    .string "La di da di da....$"

MtMoon_B2F_Text_ImakuniIntro2::
    .string "Hey, hey!\n"
    .string "Little miss!\p"
    .string "Who is cuter, Pikachu or me?\p"
    .string "... ...\n"
    .string "... ...\p"
    .string "... ...\n"
    .string "... ...\p"
    .string "What? What's the deal?\p"
    .string "It's me, Imakuni?!\n"
    .string "The friendly musician and pop star!\p"
    .string "I'm just an innocent friend dressed\n"
    .string "in all black in the mountains.\p"
    .string "Here, I'll sing the Pokémon theme\n"
    .string "to show you I'm a good guy.\p"
    .string "3, 2, 1....$"

MtMoon_B2F_Text_ImakuniLoss::
    .string "Huh? I lost?\n"
    .string "Don't tell anyone that I'd lose!$"

MtMoon_B2F_Text_ImakuniPostFight::
    .string "Well, that was refreshing!\p"
    .string "Those were some strange Pokémon you\n"
    .string "used, though. Very unusual.\p"
    .string "Huh? Puppets? I have no\n"
    .string "idea what you're talking about.\p"
    .string "And anyway, I must get going.\n"
    .string "I have more places to perform at!$"
