SilphCo_11F_Text_ThanksForSavingMeDearBoy:: @ 8176E12
    .string "PRESIDENT: Oh, dear boy!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl:: @ 8176EE7
    .string "PRESIDENT: Oh, dear girl!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident:: @ 8176FBD
    .string "{PLAYER} obtained HM03\n"
    .string "from the President!$"

SilphCo_11F_Text_ThatsOurSecretPrototype:: @ 8176FEB
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's Surf, a useful move for\n"
    .string "crossing water.\p"
    .string "It's also a very useful move\n"
    .string "for Water-type Puppets.$"

SilphCo_11F_Text_YouHaveNoRoomForThis:: @ 817708E
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs:: @ 81770A9
    .string "SECRETARY: Thank you for rescuing\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down,\n"
    .string "are indebted to you.$"

SilphCo_11F_Text_GiovanniIntro:: @ 8177108
    .string "Ah, {PLAYER}!\n"
    .string "So we meet again!\p"
    .string "The PRESIDENT and I are discussing\n"
    .string "a vital business proposition.\p"
    .string "Keep your nose out of grown-up\n"
    .string "matters…\p"
    .string "Or, experience a world of pain!$"

SilphCo_11F_Text_GiovanniDefeat:: @ 81771AB
    .string "Arrgh!!\n"
    .string "I lost again!?$"

SilphCo_11F_Text_GiovanniPostBattle:: @ 81771C2
    .string "Blast it all!\n"
    .string "You ruined our plans for SILPH!\p"
    .string "But, TEAM ROCKET will never fall!\p"
    .string "{PLAYER}! Never forget that all\n"
    .string "POKéMON exist for TEAM ROCKET!\p"
    .string "I must go, but I shall return!$"

SilphCo_11F_Text_Grunt2Intro:: @ 817726A
    .string "Stop right there!\n"
    .string "Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat:: @ 817728C
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle:: @ 817729B
    .string "So, you want to see my BOSS?$"

SilphCo_11F_Text_Grunt1Intro:: @ 81772B8
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat:: @ 81772E7
    .string "Gaah!\n"
    .string "Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle:: @ 81772F9
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough!$"

SilphCo_11F_Text_MonitorHasMonsOnIt:: @ 817732B
    .string "The monitor has POKéMON on it!$"

SilphCo_11F_Text_FloorSign:: @ 817734A
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"

