CinnabarIsland_Gym_Text_BlaineIntro:: @ 8199543
    .string "Hah!\p"
    .string "I am Blaine, the red-hot Leader\n"
    .string "of Cinnabar Gym!\p"
    .string "My fiery Puppets are all rough\n"
    .string "and ready with intense heat!\p"
    .string "They incinerate all challengers!\p"
    .string "Hah!\n"
    .string "You better have BURN HEAL!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat:: @ 81995FA
    .string "I have burned down to nothing!\n"
    .string "Not even ashes remain!\p"
    .string "You have earned the VolcanoBadge.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove:: @ 8199652
    .string "Fire Blast is the ultimate fire\n"
    .string "technique.\p"
    .string "Don't waste it on Water Puppets.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge:: @ 819969E
    .string "Hah!\p"
    .string "The VolcanoBadge shows that your\n"
    .string "Puppets can take the heat.\p"
    .string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine:: @ 81996FF
    .string "{PLAYER} received TM38\n"
    .string "from Blaine.$"

CinnabarIsland_Gym_Text_BlainePostBattle:: @ 819971D
    .string "TM38 contains Fire Blast.\n"
    .string "Teach it to Fire-type Puppets.\p"
    .string "Utsuho or Yuki would be\n"
    .string "ideal for that move.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis:: @ 8199789
    .string "Make space for this, child!$"

CinnabarIsland_Gym_Text_ErikIntro:: @ 81997A5
    .string "Do you know how hot Puppet fire\n"
    .string "can get?$"

CinnabarIsland_Gym_Text_ErikDefeat:: @ 81997D6
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle:: @ 81997EA
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro:: @ 819983F
    .string "I was a thief, but I went straight\n"
    .string "as a Trainer.$"

CinnabarIsland_Gym_Text_QuinnDefeat:: @ 8199870
    .string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle:: @ 819987D
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's Puppets.$"

CinnabarIsland_Gym_Text_AveryIntro:: @ 81998BD
    .string "I've studied Puppets thoroughly.\n"
    .string "You can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat:: @ 81998ED
    .string "Waah!\n"
    .string "My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle:: @ 8199911
    .string "My theories are too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_RamonIntro:: @ 8199948
    .string "I like using Fire-type Puppets.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_RamonDefeat:: @ 8199973
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle:: @ 8199986
    .string "I like using Marisa, since she's\n"
    .string "a thief Puppet.$"

CinnabarIsland_Gym_Text_DerekIntro:: @ 81999B7
    .string "I know why Blaine became a\n"
    .string "Trainer.$"

CinnabarIsland_Gym_Text_DerekDefeat:: @ 81999DB
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle:: @ 81999DF
    .string "Our Leader, Blaine, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "Puppet appeared.\p"
    .string "Its light allowed Blaine to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro:: @ 8199A7F
    .string "I've been to many Gyms, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat:: @ 8199AB9
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle:: @ 8199AC9
    .string "Fire Punch…\n"
    .string "Is not always the right answer?$"

CinnabarIsland_Gym_Text_ZacIntro:: @ 8199AFC
    .string "Fire is weak against H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat:: @ 8199B16
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle:: @ 8199B27
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the Fire\n"
    .string "type beats Ice-type Puppets.$"

CinnabarIsland_Gym_Text_GymGuyAdvice:: @ 8199B81
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded Blaine is a Fire\n"
    .string "Puppet pro.\p"
    .string "Douse his spirits with water!\p"
    .string "You'd better take some\n"
    .string "Burn Heals, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory:: @ 8199C0C
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue:: @ 8199C29
    .string "CINNABAR PUPPETRY GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{OTHER_PC}, {RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon:: @ 8199C62
    .string "CINNABAR PUPPETRY GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{OTHER_PC}, {RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules:: @ 8199C9F
    .string "Puppetry Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a Trainer!\p"
    .string "If you want to conserve your\n"
    .string "Puppets for the Gym Leader…\p"
    .string "Then get it right!\n"
    .string "Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1:: @ 8199D5A
    .string "Sunny, Luna, and Star are called\n"
	.string "the Three Elemental Fairies?$"

CinnabarIsland_Gym_Text_QuizQuestion2:: @ 8199D79
    .string "Evolving Chibi Rin to Speed Rin\n"
    .string "can create a Zombie Fairy?$"

CinnabarIsland_Gym_Text_QuizQuestion3:: @ 8199DA9
    .string "TM51 contains Fiery Dance?$"

CinnabarIsland_Gym_Text_QuizQuestion4:: @ 8199DC6
    .string "TCirno can learn Flamethrower?$"

CinnabarIsland_Gym_Text_QuizQuestion5:: @ 8199E00
    .string "Which of these moves is the safest\n"
    .string "and most effective to use on Chiyari?$"

CinnabarIsland_Gym_Text_QuizQuestion6:: @ 8199E36
    .string "Which of these Puppets is the best\n"
	.string "choice to take hits from Mimi-chan?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough:: @ 8199E4F
    .string "You're absolutely correct!\p"
    .string "Go on through!$"

CinnabarIsland_Gym_Text_SorryBadCall:: @ 8199E79
    .string "Sorry!\n"
    .string "Bad call!$"

