FuchsiaCity_House3_Text_WouldYouLikeToForgetMove:: @ 81993B9
    .string "Uh…\n"
    .string "Oh, yes, I'm the Move Deleter.\p"
    .string "I can make Puppets forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove:: @ 8199421
    .string "Which Puppet should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten:: @ 8199445
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove:: @ 8199465
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten:: @ 8199485
    .string "{STR_VAR_1}'s {STR_VAR_2}\n"
    .string "should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely:: @ 81994B1
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves:: @ 81994EA
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves:: @ 819951F
    .string "What?\n"
    .string "No EGG should know any moves.$"

