Route9_Text_AliciaIntro:: @ 81847B7
    .string "You have Puppets with you!\n"
    .string "You're mine!$"

Route9_Text_AliciaDefeat:: @ 81847DF
    .string "You deceived me…$"

Route9_Text_AliciaPostBattle:: @ 81847F0
    .string "The tunnel coming up is pitch-black\n"
    .string "inside.\p"
    .string "You'll need Flash to get through\n"
    .string "there.$"

Route9_Text_ChrisIntro:: @ 8184844
    .string "Who's that walking there with those\n"
    .string "good-looking Puppets?$"

Route9_Text_ChrisDefeat:: @ 818487E
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle:: @ 8184890
    .string "Keep walking!$"

Route9_Text_DrewIntro:: @ 818489E
    .string "I'm taking the Rock Tunnel to\n"
    .string "go to Lavender…$"

Route9_Text_DrewDefeat:: @ 81848CC
    .string "Can't measure up…$"

Route9_Text_DrewPostBattle:: @ 81848DE
    .string "Are you off to Rock Tunnel, too?$"

Route9_Text_CaitlinIntro:: @ 81848FF
    .string "Don't you dare patronize me!$"

Route9_Text_CaitlinDefeat:: @ 818491C
    .string "No!\n"
    .string "You're too much.$"

Route9_Text_CaitlinPostBattle:: @ 8184931
    .string "You're obviously talented.\n"
    .string "Good luck to you!$"

Route9_Text_JeremyIntro:: @ 818495E
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat:: @ 818497F
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "I'm out of Puppets!$"

Route9_Text_JeremyPostBattle:: @ 81849B0
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"

Route9_Text_BriceIntro:: @ 81849DF
    .string "Hahaha!\n"
    .string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat:: @ 8184A04
    .string "What's that?$"

Route9_Text_BricePostBattle:: @ 8184A11
    .string "Hahaha!\n"
    .string "Kids should be tough!$"

Route9_Text_BrentIntro:: @ 8184A2F
    .string "I got up early every day to get\n"
    .string "snacks for my fairies!$"

Route9_Text_BrentDefeat:: @ 8184A6A
    .string "WHAT?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle:: @ 8184A8C
    .string "I have to collect more than fairies\n"
    .string "to get stronger…$"

Route9_Text_AlanIntro:: @ 8184ABE
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat:: @ 8184AD5
    .string "Hahahaha!\n"
    .string "You beat me fair!$"

Route9_Text_AlanPostBattle:: @ 8184AF1
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro:: @ 8184B18
    .string "Go, my super fairy Puppets!$"

Route9_Text_ConnerDefeat:: @ 8184B32
    .string "My fairies…$"

Route9_Text_ConnerPostBattle:: @ 8184B3B
    .string "If you don't like fairy Puppets,\n"
    .string "don't talk to me!$"

Route9_Text_RouteSign:: @ 8184B66
    .string "ROUTE 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"

Route9_Text_MamizouNoBadgeNoBike::
	.string "Hoo...\n"
	.string "Quite unprepared, aren't we?\p"
	.string "You don't have a bike, or the\n"
	.string "Vermillion City Gym Badge.\p"
	.string "I won't stop you from going ahead,\n"
	.string "but things might be a bit\l"
	.string "inconvenient without those.$"

Route9_Text_MamizouNoBadgeYesBike::
	.string "Hohoho.\n"
	.string "A bit unprepared, aren't we?\p"
	.string "I won't stop you, but it might be a\n"
	.string "bit inconvenient going ahead without\l"
	.string "the Vermillion City Gym badge.$"

Route9_Text_MamizouYesBadgeNoBike::
	.string "Hohoho.\n"
	.string "A bit unprepared, aren't we?\p"
	.string "I won't stop you, but it might\n"
	.string "be a bit inconvenient going\l"
	.string "ahead without a Bicycle.$"

Route9_Text_MamizouYesBadgeYesBike::
	.string "Hohoho.\n"
	.string "Nice weather, isn't it?$"

Route9_Text_MamizouBadgering::
	.string "What?\n"
	.string "Is something the matter?\n"
