CeruleanCity_Mart_Text_RepelWorksOnWeakMons:: @ 81929C2
    .string "Repel not only keeps bugs away,\n"
    .string "it also works on weak Puppets.\p"
    .string "Put your strongest Puppet at the\n"
    .string "front of the party.\p"
    .string "If your first Puppet is strong,\n"
    .string "Repel's effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy:: @ 8192A79
    .string "Do you know about Rare Candy?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes Puppets grow\n"
    .string "very quickly all of a sudden.$"

