LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere:: @ 819358E
    .string "I recently moved to this town.\p"
    .string "I hear that Mr. Fuji's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo:: @ 81935ED
    .string "That's odd, Mr. Fuji isn't here.\n"
    .string "Where'd he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother:: @ 819361D
    .string "Mr. Fuji had been praying alone\n"
    .string "for Cubone's friend.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons:: @ 8193652
    .string "This is really Mr. Fuji's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned Pokémon and Puppets.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug:: @ 81936B4
    .string "It's so warm!\n"
    .string "Pokémon are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino:: @ 81936DE
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck:: @ 81936EE
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis:: @ 81936FF
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your Tohodex quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for Puppets,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji:: @ 81937BD
    .string "{PLAYER} received a Merlin Flute\n"
    .string "from Mr. Fuji.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute:: @ 81937E5
    .string "Upon hearing the Merlin Flute,\n"
    .string "sleeping Puppets will spring awake.\p"
    .string "Try using it on the pink blobs\n"
    .string "that are sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis:: @ 819385B
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou:: @ 8193878
    .string "MR. FUJI: Has my Merlin Flute\n"
    .string "helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped:: @ 81938A0
    .string "POKéMON FAN MAGAZINE\n"
    .string "Monthly Grand Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf:: @ 819392B
    .string "Pokémon magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

