
BattleTowerLobby_Text_DidntSaveBeforeQuitting::
	.string "{COLOR RED}Excuse me!\p"
	.string "You didn't save before you quit your\n"
	.string "challenge last time.\p"
	.string "Because of that, your challenge so\n"
	.string "far has been disqualified. Sorry!$"

BattleTowerLobby_Text_WeveBeenWaitingForYou::
	.string "We've been waiting for you!\p"
	.string "$"

BattleTowerLobby_Text_ProgressWillBeSaved::
	.string "Before entering a Battle Room, your\n"
	.string "progress will be saved. Please wait.$"

BattleTowerLobby_Text_Congratulations::
	.string "Congratulations!\n"
	.string "You've beaten all seven Trainers!$"

BattleTowerLobby_Text_ThankYouForPlaying::
	.string "Thank you for playing!\p"
	.string "$"
	
BattleTowerLobby_Text_RecordSaving::
	.string "Your record will be saved.\n"
	.string "Please wait.$"
	
BattleTowerLobby_Text_GainPrize::
	.string "For beating seven Trainers in a row,\n"
	.string "you have earned this fabulous prize!\p"
	.string "not yet, WIP$"

BattleTowerLobby_Text_LookingForward::
	.string "We'll be looking forward to your\n"
	.string "next challenge.$"

BattleTowerLobby_Text_IllDirectYou::
	.string "I'll direct you to your Battle Room now.$"

BattleTowerLobby_Text_Welcome::
	.string "Welcome to the Battle Tower!\p"
	.string "Please register with me to enter\n"
	.string "a Battle Room.$"

BattleTowerLobby_Text_MakeAChallenge::
	.string "Would you like to make a Battle Room\n"
	.string "challenge?$"

BattleTowerLobby_Text_Explanation::
	.string "The Battle Tower is a facility made\n"
	.string "especially for Puppet battles.\p"
	.string "Within the Tower are many Battle\nRooms.\p"
	.string "In each Battle Room, seven Trainers\n"
	.string "await your challenge.\p"
	.string "Beat all seven, and you will be rewarded\n"
	.string "with BP to trade for prizes.\p"
	.string "You may also take a break from your\n"
	.string "challenge by saving your progress.\p"
	.string "For the duration of the challenge,\n"
	.string "your Puppets will be set to level 50.\p"
	.string "Make sure you save properly or you\n"
	.string "won't be able to continue.$"

BattleTower_Lobby_Text_LookingForward::
	.string "We'll be looking forward to your\n"
	.string "next challenge.$"

BattleTower_Lobby_Text_WhichRoom::
	.string "There are two Battle Rooms,\n"
	.string "Standard and Factory.\l"
	.string "Which would you like to challenge?$"

BattleTower_Lobby_Text_MustHaveThreeEligible::
	.string "Excuse me!\p"
	.string "You don't have three eligible\n"
	.string "Puppets.\p"
	.string "You must have three different\n"
	.string "Puppets to enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "Eggs{STR_VAR_1} ineligible.\p"
	.string "Please come see me when you are\n"
	.string "ready.$"

BattleTower_Lobby_Text_PleaseSelectPuppets::
	.string "Please select the Puppets you wish\n"
	.string "to enter.$"

BattleTower_Lobby_Text_BeforeEnteringMustSave::
	.string "Before entering a Battle Room, your\n"
	.string "progress must be saved.\n"
	.string "Is that okay?$"

BattleTower_Lobby_Text_IllDirectYou::
	.string "I'll direct you to your Battle Room\n"
	.string "now.$"
