Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers:: @ 819E523
    .string "The types of Puppets match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000:: @ 819E59D
    .string "A Nugget is totally useless.\n"
    .string "So I sold it for ¥5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender:: @ 819E5D2
    .string "I heard that ghosts haunt\n"
    .string "Lavender Town.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons:: @ 819E5FB
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "Aides to Prof. Oak.\p"
    .string "If your Tohodex has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from Prof. Oak.\p"
    .string "He entrusted me with this\n"
    .string "Exp. Share.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of Puppets?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo:: @ 819E733
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of Puppets!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide:: @ 819E786
    .string "{PLAYER} received the Exp. Share\n"
    .string "from the Aide.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone:: @ 819E7AF
    .string "Exp. Share is an item to be held\n"
    .string "by a Puppet.\p"
    .string "The Puppet will receive a share\n"
    .string "of the Exp. Points without having\l"
    .string "to battle.$"

