#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("A plain attack.");
const u8 gMoveDescription_KarateChop[] = _("High critical rate.");
const u8 gMoveDescription_Feint[] = _("+2 Priority.\nBypasses Detect.");
const u8 gMoveDescription_CometPunch[] = _("Hits 2-5 times.");
const u8 gMoveDescription_MegaPunch[] = _("A plain attack.");
const u8 gMoveDescription_PayDay[] = _("Creates money equal\nto 5 times the\nuser's level.");
const u8 gMoveDescription_FirePunch[] = _("10%: Burn foe.");
const u8 gMoveDescription_IcePunch[] = _("10%: Freeze foe.");
const u8 gMoveDescription_ThunderPunch[] = _("10%: Paralyze foe.");
const u8 gMoveDescription_Scratch[] = _("A plain attack.");
const u8 gMoveDescription_NightSlash[] = _("High critical rate.");
const u8 gMoveDescription_Judgment[] = _("OHKOs foe via holy\npower. Fails if foe\nis higher level.");
const u8 gMoveDescription_RazorWind[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_SwordsDance[] = _("+2 Attack.");
const u8 gMoveDescription_Cut[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_Gust[] = _("Hits even foes that\nare in the sky.");
const u8 gMoveDescription_WingAttack[] = _("30%: Foe flinches.");
const u8 gMoveDescription_Whirlwind[] = _("Forces foe switch.\nIn the wild, ends\nthe fight outright.");
const u8 gMoveDescription_Fly[] = _("A 2-turn attack.\nThe user avoids\nharm between turns\nby flying high.");
const u8 gMoveDescription_Bind[] = _("Constricts the foe\nfor 4-5 turns,\npreventing escape.");
const u8 gMoveDescription_Braver[] = _("20%: -1 Defense.");
const u8 gMoveDescription_VineWhip[] = _("A plain attack.");
const u8 gMoveDescription_Stomp[] = _("30%: Foe flinches.\nIf foe has used\nMinimize, inflicts\ndouble damage.");
const u8 gMoveDescription_DoubleKick[] = _("Hits twice.");
const u8 gMoveDescription_MegaKick[] = _("A plain attack.");
const u8 gMoveDescription_JumpKick[] = _("If it fails to hit,\nuser loses half of\ntheir max HP.");
const u8 gMoveDescription_RollingKick[] = _("20%: Foe flinches.");
const u8 gMoveDescription_SandAttack[] = _("-1 Accuracy.");
const u8 gMoveDescription_Headbutt[] = _("20%: Foe flinches.");
const u8 gMoveDescription_KnifeThrow[] = _("A plain attack.");
const u8 gMoveDescription_MagicKnife[] = _("Hits 2-5 times.");
const u8 gMoveDescription_Sculpture[] = _("Won't miss unless\nentirely unable to\nhit the foe.\nBypasses Detect.");
const u8 gMoveDescription_Tackle[] = _("A plain attack.");
const u8 gMoveDescription_BodySlam[] = _("30%: Paralyze foe.");
const u8 gMoveDescription_Wrap[] = _("Constricts the foe\nfor 4-5 turns,\npreventing escape.");
const u8 gMoveDescription_TakeDown[] = _("User takes recoil\nequal to 25% of\ndamage dealt.");
const u8 gMoveDescription_Thrash[] = _("-1 Own Defense.");
const u8 gMoveDescription_DoubleEdge[] = _("User takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_TailWhip[] = _("-1 Defense.");
const u8 gMoveDescription_PoisonSting[] = _("30%: Poison foe.");
const u8 gMoveDescription_SealNeedle[] = _("30%: Paralyze foe.");
const u8 gMoveDescription_PinMissile[] = _("Hits 2-5 times.");
const u8 gMoveDescription_Leer[] = _("-1 Defense.");
const u8 gMoveDescription_Bite[] = _("30%: Foe flinches.");
const u8 gMoveDescription_Growl[] = _("-1 Attack.");
const u8 gMoveDescription_Roar[] = _("Forces foe switch.\nIn the wild, ends\nthe fight outright.");
const u8 gMoveDescription_Sing[] = _("Inflicts sleep.");
const u8 gMoveDescription_Jamming[] = _("Traps the foe,\npreventing escape.");
const u8 gMoveDescription_SonicBoom[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_Disable[] = _("Disables the last\nmove used by the\nfoe.");
const u8 gMoveDescription_PoisonTears[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_Ember[] = _("10%: Burn foe.");
const u8 gMoveDescription_Flamethrower[] = _("10%: Burn foe.");
const u8 gMoveDescription_Mist[] = _("For 5 turns, foes\ncannot lower ally\nstats.");
const u8 gMoveDescription_WaterGun[] = _("A plain attack.");
const u8 gMoveDescription_HydroPump[] = _("A plain attack.");
const u8 gMoveDescription_Surf[] = _("A plain attack.");
const u8 gMoveDescription_IceBeam[] = _("10%: Freeze foe.");
const u8 gMoveDescription_Blizzard[] = _("10%: Freeze foe.\nIn hail, won't miss\nunless entirely\nunable to hit.");
const u8 gMoveDescription_Psybeam[] = _("30%: Confuse foe.");
const u8 gMoveDescription_BubbleBeam[] = _("30%: -1 Speed.");
const u8 gMoveDescription_AuroraBeam[] = _("30%: -1 Attack.");
const u8 gMoveDescription_HyperBeam[] = _("20%: -1 Sp. Def.");
const u8 gMoveDescription_Peck[] = _("A plain attack.");
const u8 gMoveDescription_FoulPlay[] = _("Uses the foe's\nAttack stat instead\nof the user's.");
const u8 gMoveDescription_Submission[] = _("User takes recoil\nequal to 25% of\ndamage dealt.");
const u8 gMoveDescription_SkandasLeg[] = _("30%: Foe flinches.");
const u8 gMoveDescription_Counter[] = _("-5 priority. If\nuser takes physical\ndamage, inflict it\nback doubled.");
const u8 gMoveDescription_SeismicToss[] = _("Inflicts damage\nequal to the user's\nlevel.");
const u8 gMoveDescription_Strength[] = _("10%: +1 Attack.");
const u8 gMoveDescription_Absorb[] = _("User recovers half\nthe damage dealt.");
const u8 gMoveDescription_MegaDrain[] = _("User recovers half\nthe damage dealt.");
const u8 gMoveDescription_LeechSeed[] = _("Absorbs 1/8 of the\nfoe's HP each turn.");
const u8 gMoveDescription_Growth[] = _("+1 Attack.\n+1 Sp. Atk.\nIn strong sunlight,\ndouble the effects.");
const u8 gMoveDescription_RazorLeaf[] = _("High critical rate.");
const u8 gMoveDescription_SolarBeam[] = _("A 2-turn attack. In\nsunlight, instant.\nIn bad weather,\ndamage is halved.");
const u8 gMoveDescription_PoisonPowder[] = _("Poison foe.");
const u8 gMoveDescription_StunSpore[] = _("Paralyze foe.");
const u8 gMoveDescription_SleepPowder[] = _("Inflicts sleep.");
const u8 gMoveDescription_PetalStorm[] = _("20%: +1 Attack.");
const u8 gMoveDescription_Mesmerism[] = _("20%: Confuse foe.");
const u8 gMoveDescription_DarkPulse[] = _("20%: Foe flinches.");
const u8 gMoveDescription_FireSpin[] = _("Ensnares the foe\nfor 4-5 turns,\npreventing escape.");
const u8 gMoveDescription_ThunderShock[] = _("10%: Paralyze foe.");
const u8 gMoveDescription_Thunderbolt[] = _("10%: Paralyze foe.");
const u8 gMoveDescription_ThunderWave[] = _("Paralyze foe.\nFails against Earth\ntype puppets.");
const u8 gMoveDescription_Thunder[] = _("30%: Paralyze foe.\nWon't miss in rain.\nIn sun, 50% Acc.\nHits airborne foes.");
const u8 gMoveDescription_RockWrecker[] = _("20%: +1 Defense.");
const u8 gMoveDescription_Earthquake[] = _("If foe is under-\nground, won't miss\nunless entirely\nunable to hit.");
const u8 gMoveDescription_Fissure[] = _("OHKOs foe via open\ncrevice under them.\nFails if foe is\nhigher level.");
const u8 gMoveDescription_Dig[] = _("A 2-turn attack.\nThe user avoids\nharm between turns\nby digging down.");
const u8 gMoveDescription_Toxic[] = _("Badly poisons foe.\nWon't miss if user\nis Miasma-type.\n");
const u8 gMoveDescription_Psyshot[] = _("10%: Confuses foe.");
const u8 gMoveDescription_ManaBurst[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_Hypnosis[] = _("Inflicts sleep.");
const u8 gMoveDescription_ZenHeadbutt[] = _("20%: Foe flinches.");
const u8 gMoveDescription_Agility[] = _("+2 Speed.");
const u8 gMoveDescription_QuickAttack[] = _("+1 Priority.");
const u8 gMoveDescription_Rage[] = _("100%: Burns self.");
const u8 gMoveDescription_Teleport[] = _("The user switches.\nIn the wild, ends\nthe fight outright.");
const u8 gMoveDescription_NightShade[] = _("Inflicts damage\nequal to the user's\nlevel.");
const u8 gMoveDescription_Mimic[] = _("The user learns the\nlast move the foe\nused temporarily.");
const u8 gMoveDescription_Screech[] = _("-2 Defense.");
const u8 gMoveDescription_DoubleTeam[] = _("+1 Evasion.");
const u8 gMoveDescription_Recover[] = _("Restores half of\nthe user's max HP.");
const u8 gMoveDescription_Harden[] = _("+1 Defense.");
const u8 gMoveDescription_Minimize[] = _("+1 Evasion.");
const u8 gMoveDescription_Smokescreen[] = _("-1 Accuracy.");
const u8 gMoveDescription_ConfuseRay[] = _("Confuses foe.");
const u8 gMoveDescription_Withdraw[] = _("+1 Defense.");
const u8 gMoveDescription_DefenseCurl[] = _("+1 Defense.");
const u8 gMoveDescription_Barrier[] = _("+2 Defense.");
const u8 gMoveDescription_LightScreen[] = _("For 5 turns, allies\ntake half damage\nfrom Special hits.");
const u8 gMoveDescription_Haze[] = _("Resets all stat\nchanges back to +0\nfor all puppets.");
const u8 gMoveDescription_Reflect[] = _("For 5 turns, allies\ntake half damage\nfrom Physical hits.");
const u8 gMoveDescription_FocusEnergy[] = _("Improves the user's\ncritical hit rate\nsharply.");
const u8 gMoveDescription_WorkUp[] = _("+1 Attack.\n+1 Sp. Atk.");
const u8 gMoveDescription_Metronome[] = _("User randomly uses\nalmost any move in\nexistence.");
const u8 gMoveDescription_DebtSpiral[] = _("Consumes money equal\nto 20 times the\nuser's level.");
const u8 gMoveDescription_SelfDestruct[] = _("The user faints.");
const u8 gMoveDescription_MindBomb[] = _("Has Power equal to\nthe foe's Cost.");
const u8 gMoveDescription_Lick[] = _("30%: Paralyze foe.");
const u8 gMoveDescription_Smog[] = _("40%: Poison foe.");
const u8 gMoveDescription_GunkShot[] = _("30%: Poison foe.");
const u8 gMoveDescription_WoodHammer[] = _("User takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_FireBlast[] = _("10%: Burn foe.");
const u8 gMoveDescription_Waterfall[] = _("20%: Foe flinches.");
const u8 gMoveDescription_ManaShield[] = _("+1 Sp. Def.");
const u8 gMoveDescription_Swift[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_SkullBash[] = _("A 2-turn attack.\nOn first turn, user\ngains +1 Defense.");
const u8 gMoveDescription_Danmaku[] = _("A plain attack.");
const u8 gMoveDescription_TopsyTurvy[] = _("Inverts the foe's\nstat changes.");
const u8 gMoveDescription_Amnesia[] = _("+2 Sp. Def.");
const u8 gMoveDescription_LunaDial[] = _("100%: Freezes foe.");
const u8 gMoveDescription_SoftBoiled[] = _("Restores half of\nthe user's max HP.\nOn the field, gives\nown HP to allies.");
const u8 gMoveDescription_HiJumpKick[] = _("If it fails to hit,\nuser loses half of\ntheir max HP.");
const u8 gMoveDescription_Daunt[] = _("Drains PP from the\nfoe's last used\nmove.");
const u8 gMoveDescription_DreamEater[] = _("User recovers half\nthe damage dealt.\n(Does not require\na sleeping foe.)");
const u8 gMoveDescription_OminousWind[] = _("30%: -1 Speed.");
const u8 gMoveDescription_Barrage[] = _("Hits 3 times.");
const u8 gMoveDescription_LeechLife[] = _("User recovers half\nthe damage dealt.");
const u8 gMoveDescription_LovelyKiss[] = _("Inflicts sleep.");
const u8 gMoveDescription_SkyAttack[] = _("A 2-turn attack.\n80%: Foe flinches.\nHigh critical rate.");
const u8 gMoveDescription_Transform[] = _("Transforms into the\nfoe, copying stats,\nAbility, moveset,\nand species.");
const u8 gMoveDescription_Bubble[] = _("10%: -1 Speed.");
const u8 gMoveDescription_DizzyPunch[] = _("20%: Confuse foe.");
const u8 gMoveDescription_BurnPowder[] = _("Burns foe.");
const u8 gMoveDescription_Flash[] = _("30%: -1 Accuracy.");
const u8 gMoveDescription_Psywave[] = _("Inflicts damage\nequal to the user's\nlevel.");
const u8 gMoveDescription_Splash[] = _("Bounces around.\nDoes not have any\npractical effect.");
const u8 gMoveDescription_Disperse[] = _("+2 Defense.");
const u8 gMoveDescription_AquaJet[] = _("+1 Priority");
const u8 gMoveDescription_Explosion[] = _("The user faints.");
const u8 gMoveDescription_FurySwipes[] = _("Hits 2-5 times.");
const u8 gMoveDescription_SuckerPunch[] = _("+1 Priority.\nFails if foe is not\nreadying a damage-\ndealing attack.");
const u8 gMoveDescription_Rest[] = _("Restores all HP,\nbut the user falls\nasleep for 2 turns.");
const u8 gMoveDescription_RockSlide[] = _("30%: Foe flinches.");
const u8 gMoveDescription_KillingBite[] = _("20%: Foe flinches.");
const u8 gMoveDescription_Sharpen[] = _("+1 Attack.");
const u8 gMoveDescription_Conversion[] = _("Changes type to\nmatch the first\nknown move.");
const u8 gMoveDescription_TriAttack[] = _("20%: Burn, Freeze,\nor Paralyze foe.");
const u8 gMoveDescription_GigaImpact[] = _("If it fails to hit,\nuser loses half of\ntheir max HP.");
const u8 gMoveDescription_Slash[] = _("High critical rate.");
const u8 gMoveDescription_Substitute[] = _("Uses 25% of own HP\nto create a decoy.\nBlocks most status\nmoves.");
const u8 gMoveDescription_Struggle[] = _("An attack that is\nused only if there\nis no PP. It also\nhurts the user.");
const u8 gMoveDescription_Sketch[] = _("The user learns the\nlast move the foe\nused permanently.");
const u8 gMoveDescription_ShadowSneak[] = _("+1 Priority.");
const u8 gMoveDescription_Thief[] = _("Steals the foe's\nheld item, if not\ncurrently holding\nanything.");
const u8 gMoveDescription_SpiderWeb[] = _("100%: Paralyze foe.");
const u8 gMoveDescription_HeartsEye[] = _("-2 Sp. Def.");
const u8 gMoveDescription_Nightmare[] = _("10%: Inflict sleep.");
const u8 gMoveDescription_FlameWheel[] = _("30%: Inflict burn.\nCan be used while\nfrozen.");
const u8 gMoveDescription_Snore[] = _("50%: Foe flinches.\nOnly usable while\nasleep.");
const u8 gMoveDescription_Curse[] = _("If Ghost: use 50%\nof HP to sap 25%.\nElse: -1 Speed,\n+1 Attack, Defense.");
const u8 gMoveDescription_Flail[] = _("Power rises if user\nhas very low HP.\nMax power is 200,\nmin is 40.");
const u8 gMoveDescription_Conversion2[] = _("If Conversion is so\nbad, how come they\nmade a sequel?");
const u8 gMoveDescription_Aeroblast[] = _("High critical rate.");
const u8 gMoveDescription_CottonSpore[] = _("-2 Speed.");
const u8 gMoveDescription_Reversal[] = _("Power rises if user\nhas very low HP.\nMax power is 200,\nmin is 40.");
const u8 gMoveDescription_Spite[] = _("Drains PP from the\nfoe's last used\nmove.");
const u8 gMoveDescription_PowderSnow[] = _("10%: Freeze foe.");
const u8 gMoveDescription_Protect[] = _("+1 Defense.\n+1 Sp. Def.");
const u8 gMoveDescription_MachPunch[] = _("+1 Priority.");
const u8 gMoveDescription_ScaryFace[] = _("-2 Speed.");
const u8 gMoveDescription_FaintAttack[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_SweetKiss[] = _("Confuses foe.");
const u8 gMoveDescription_BellyDrum[] = _("Sets Attack to +6.\nConsumes half of\nthe user's max HP.");
const u8 gMoveDescription_SludgeBomb[] = _("20%: Poison foe.");
const u8 gMoveDescription_MudSlap[] = _("100%: -1 Accuracy.");
const u8 gMoveDescription_BlackRipple[] = _("20%: Paralyze foe.");
const u8 gMoveDescription_Spikes[] = _("Spikes hurt foes as\nthey switch in. Can\nbe stacked up to\nthree times.");
const u8 gMoveDescription_Discharge[] = _("30%: Paralyze foe.");
const u8 gMoveDescription_Foresight[] = _("Removes immunities\nof Ghost-types, and\nlocks foe's Evasion\nto at most +0.");
const u8 gMoveDescription_DestinyBond[] = _("If user is knocked\nout by an attack,\nthe foe faints as\nwell.");
const u8 gMoveDescription_PerishSong[] = _("Anyone hearing the\nsong faints in 3\nturns, including\nthe user.");
const u8 gMoveDescription_IcyWind[] = _("100%: -1 Speed.");
const u8 gMoveDescription_Detect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_HeadRush[] = _("Hits 2-5 times.\n\n100%: Headache.");
const u8 gMoveDescription_LockOn[] = _("+2 Accuracy.");
const u8 gMoveDescription_Outrage[] = _("20%: Foe flinches.");
const u8 gMoveDescription_Sandstorm[] = _("For 5 turns, non-\nearthen types take\ndamage. Beasts\ngain +50% Sp. Def.");
const u8 gMoveDescription_GigaDrain[] = _("User recovers half\nthe damage dealt.");
const u8 gMoveDescription_Endure[] = _("Withstand damage\nwith at least 1 HP.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_Charm[] = _("-2 Attack.");
const u8 gMoveDescription_Tremors[] = _("100%: -1 Speed.");
const u8 gMoveDescription_FalseSwipe[] = _("Always leaves the\nfoe with at least\n1 HP.");
const u8 gMoveDescription_Swagger[] = _("+2 Foe's Attack.\nConfuses foe.");
const u8 gMoveDescription_Hospitality[] = _("Inflicts sleep.\nOn the field, gives\nown HP to allies.");
const u8 gMoveDescription_Spark[] = _("30%: Paralyze foe.");
const u8 gMoveDescription_FuryCutter[] = _("Doubles in power\neach consecutive\nturn it hits.");
const u8 gMoveDescription_SteelWing[] = _("10%: +1 Defense.");
const u8 gMoveDescription_LureOfDeath[] = _("OHKOs foe by simple\ncessation of life.\nFails if foe is\nhigher level.");
const u8 gMoveDescription_Attract[] = _("Makes foes of the\nopposite mana sign\nfail to attack\nhalf of the time.");
const u8 gMoveDescription_SleepTalk[] = _("Use a random other\nknown move. Usable\nonly while asleep.");
const u8 gMoveDescription_HealBell[] = _("Heal the party of\nall status problems.");
const u8 gMoveDescription_FinalGambit[] = _("Damage is equal to\nthe user's HP.\nThe user faints.");
const u8 gMoveDescription_Prank[] = _("Damage is equal to\nhalf of the foe's\ncurrent HP.");
const u8 gMoveDescription_Frustration[] = _("A plain attack.");
const u8 gMoveDescription_Safeguard[] = _("For 5 turns, allies\nare immune to major\nstatus problems.");
const u8 gMoveDescription_PainSplit[] = _("Sets own and foe's\nHP to the average\nof the two.");
const u8 gMoveDescription_SacredFire[] = _("20%: +1 Attack.");
const u8 gMoveDescription_Magnitude[] = _("Power is random and\ndeviates wildly.");
const u8 gMoveDescription_DynamicPunch[] = _("20%: Confuses foe.");
const u8 gMoveDescription_BraveBird[] = _("User takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_LavaPlume[] = _("30%: Burn foe.");
const u8 gMoveDescription_BatonPass[] = _("The user switches\nbut passes stat\nchanges and most\nminor statuses.");
const u8 gMoveDescription_Encore[] = _("Compels the foe to\nrepeat their last\nmove for 3 turns.");
const u8 gMoveDescription_Pursuit[] = _("If foe is switching\nout, chases them\nand does double\ndamage.");
const u8 gMoveDescription_RapidSpin[] = _("Removes trapping\neffects like Wrap,\nas well as Spikes\nand Leech Seed.");
const u8 gMoveDescription_NaturePower[] = _("Has Power equal to\nthe foe's Cost.");
const u8 gMoveDescription_SteelFist[] = _("30%: -1 Defense.");
const u8 gMoveDescription_MetalClaw[] = _("10%: +1 Attack.");
const u8 gMoveDescription_VitalThrow[] = _("-1 Priority.\nKnocks off the\nfoe's held item.");
const u8 gMoveDescription_EnergyLight[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_Synthesis[] = _("Restores half of\nthe user's HP. In\nsun, gain 2/3. In\nbad weather, 1/3.");
const u8 gMoveDescription_LUNATIC[] = _("20%: -1 Sp. Def.");
const u8 gMoveDescription_HiddenPower[] = _("A plain attack.");
const u8 gMoveDescription_CrossChop[] = _("High critical rate.");
const u8 gMoveDescription_ShockSpin[] = _("Removes trapping\neffects like Wrap,\nas well as Spikes\nand Leech Seed.");
const u8 gMoveDescription_RainDance[] = _("For 5 turns, powers\nup Water moves and\nweakens Fire moves.");
const u8 gMoveDescription_SunnyDay[] = _("For 5 turns, powers\nup Fire moves and\nweakens Water\nmoves.");
const u8 gMoveDescription_Crunch[] = _("20%: -1 Defense.");
const u8 gMoveDescription_MirrorCoat[] = _("-5 priority. If\nuser takes special\ndamage, inflict it\nback doubled.");
const u8 gMoveDescription_PsychUp[] = _("The user copies the\nfoe's stat changes.");
const u8 gMoveDescription_ExtremeSpeed[] = _("+2 Priority.");
const u8 gMoveDescription_AncientPower[] = _("20%: +1 Defense.");
const u8 gMoveDescription_ShadowBall[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_PsychoCut[] = _("High critical rate.");
const u8 gMoveDescription_RockSmash[] = _("50%: -1 Defense.");
const u8 gMoveDescription_Whirlpool[] = _("Ensnares the foe\nfor 4-5 turns,\npreventing escape.");
const u8 gMoveDescription_DrawnLine[] = _("High critical rate.");
const u8 gMoveDescription_FakeOut[] = _("+3 Priority.\n100%: Foe flinches.\nOnly usable on\nthe first turn.");
const u8 gMoveDescription_Performance[] = _("Continues blindly\nfor 2-5 turns,\nduring which no one\ncan sleep.");
const u8 gMoveDescription_NastyPlot[] = _("+2 Sp. Atk.");
const u8 gMoveDescription_MirrorShot[] = _("30%: -1 Accuracy.");
const u8 gMoveDescription_AquaRing[] = _("Restores 1/16 HP\neach turn.");
const u8 gMoveDescription_HeatWave[] = _("10%: Burn foe.");
const u8 gMoveDescription_Hail[] = _("For 5 turns, non-\nIce types take\ndamage.");
const u8 gMoveDescription_Torment[] = _("Prevents the foe\nfrom using the same\nmove consecutively.");
const u8 gMoveDescription_LuckyChant[] = _("+2 Sp. Def.");
const u8 gMoveDescription_WillOWisp[] = _("Burns foe.");
const u8 gMoveDescription_Memento[] = _("-2 Attack.\n-2 Sp. Atk.\nThe user faints.");
const u8 gMoveDescription_Facade[] = _("Power doubles if\nuser is poisoned,\nburned, or\nparalyzed.");
const u8 gMoveDescription_FocusPunch[] = _("-3 Priority.\nFails if user is\nhurt by an attack.");
const u8 gMoveDescription_SmellingSalt[] = _("Paralyzed foes take\ndouble damage, but\nrecover from their\nparalysis.");
const u8 gMoveDescription_Copycat[] = _("Repeats the last\nmove that was used\nby anyone.");
const u8 gMoveDescription_RockBullet[] = _("+1 Priority.");
const u8 gMoveDescription_Charge[] = _("+1 Sp. Atk.");
const u8 gMoveDescription_Taunt[] = _("Prevents the foe\nfrom using status\nmoves for 3 turns.");
const u8 gMoveDescription_HelpingHand[] = _("A move that boosts\nthe power of the\nally's attack in a\nbattle.");
const u8 gMoveDescription_Trick[] = _("Forces foe to swap\nheld items with the\nuser.");
const u8 gMoveDescription_Recollection[] = _("Transforms into the\nfoe, copying stats,\nAbility, moveset,\nand species.");
const u8 gMoveDescription_Wish[] = _("At the end of the\nnext turn, restores\nhalf the user's HP.");
const u8 gMoveDescription_Assist[] = _("Use a random move\nknown by an ally.");
const u8 gMoveDescription_Ingrain[] = _("Restores 1/16 HP\neach turn. The user\nbecomes entirely\nunable to switch.");
const u8 gMoveDescription_Superpower[] = _("-1 Own Attack.\n-1 Own Defense.");
const u8 gMoveDescription_MagicCoat[] = _("+4 Priority.\nReflects status\nmoves back at the\nuser.");
const u8 gMoveDescription_Recycle[] = _("Recycles a consumed\nheld item.");
const u8 gMoveDescription_Revenge[] = _("-4 Priority.\nPower doubles if\nuser was hurt by\nan attack.");
const u8 gMoveDescription_BrickBreak[] = _("Shatters the foe's\nReflect and Light\nScreen, if they\nare in effect.");
const u8 gMoveDescription_Yawn[] = _("The foe becomes\ndrowsy, and falls\nasleep at the end\nof the next turn.");
const u8 gMoveDescription_KnockOff[] = _("Prevents the foe\nfrom using hold\nitems for the rest\nof the battle.");
const u8 gMoveDescription_Endeavor[] = _("Damage equals the\nfoe's HP minus\nthe user's HP.");
const u8 gMoveDescription_Eruption[] = _("Power decreases as\nthe user's HP falls\nbelow maximum.");
const u8 gMoveDescription_SkillSwap[] = _("The user and foe\nswap Abilities.");
const u8 gMoveDescription_Imprison[] = _("Makes a seal that\nprevents any foe\nfrom using moves\nthe user knows.");
const u8 gMoveDescription_Refresh[] = _("The user recovers\nfrom burn, poison,\nor paralysis.");
const u8 gMoveDescription_ShadowDance[] = _("Attacks blindly for\n2-3 turns, then\nconfuses the user.");
const u8 gMoveDescription_Snatch[] = _("+4 Priority.\nSteals any status\nmoves used that\ntarget the user.");
const u8 gMoveDescription_SecretPower[] = _("30%: ???\nEffect varies with\nthe terrain.");
const u8 gMoveDescription_ShadowForce[] = _("A 2-turn attack.\nThe user avoids\nharm between turns\nby disappearing.");
const u8 gMoveDescription_ForcePalm[] = _("30%: Paralyze foe.");
const u8 gMoveDescription_Camouflage[] = _("Changes user's type\nto match terrain.");
const u8 gMoveDescription_ManaCharge[] = _("+1 Sp. Atk.\n+1 Sp. Def.");
const u8 gMoveDescription_LusterPurge[] = _("20%: -1 Sp. Def.");
const u8 gMoveDescription_MistBall[] = _("30%: -1 Accuracy.");
const u8 gMoveDescription_Roost[] = _("Restores half of\nthe user's max HP.");
const u8 gMoveDescription_TeeterDance[] = _("Confuses foe.");
const u8 gMoveDescription_BlazeKick[] = _("High critical rate.\n10%: Burn foe.");
const u8 gMoveDescription_EarthPower[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_IceBall[] = _("10%: -1 Defense.");
const u8 gMoveDescription_NeedleArm[] = _("20%: Foe flinches.");
const u8 gMoveDescription_SlackOff[] = _("Restores half of\nthe user's max HP.");
const u8 gMoveDescription_HyperVoice[] = _("A plain attack.");
const u8 gMoveDescription_CrossPoison[] = _("High critical rate.\n10%: Poison foe.");
const u8 gMoveDescription_CrushClaw[] = _("50%: -1 Defense.");
const u8 gMoveDescription_FlareBlitz[] = _("10%: Burn foe.\nUser takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_DamBreach[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_MeteorMash[] = _("20%: -1 Speed.");
const u8 gMoveDescription_Astonish[] = _("30%: Foe flinches.");
const u8 gMoveDescription_WeatherBall[] = _("In weather, type\nchanges and power\nis doubled.");
const u8 gMoveDescription_Aromatherapy[] = _("Heal the party of\nall status problems.");
const u8 gMoveDescription_FakeTears[] = _("-2 Sp. Atk.");
const u8 gMoveDescription_AirSlash[] = _("30%: Foe flinches.");
const u8 gMoveDescription_Overheat[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_ShadowHit[] = _("High critical rate.");
const u8 gMoveDescription_RockTomb[] = _("100%: -1 Speed.");
const u8 gMoveDescription_SilverWind[] = _("30%: -1 Speed.");
const u8 gMoveDescription_BindingVoice[] = _("20%: Foe flinches.");
const u8 gMoveDescription_NatureSound[] = _("A plain attack.");
const u8 gMoveDescription_Tickle[] = _("-1 Attack.\n-1 Defense.");
const u8 gMoveDescription_DracoMeteor[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_AquaShower[] = _("Power decreases as\nthe user's HP falls\nbelow maximum.");
const u8 gMoveDescription_SignalBeam[] = _("10%: Confuse foe.");
const u8 gMoveDescription_ShadowPunch[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_Extrasensory[] = _("20%: Foe flinches.");
const u8 gMoveDescription_Soar[] = _("Hits even foes that\nare in the sky.");
const u8 gMoveDescription_SandTomb[] = _("Ensnares the foe\nfor 4-5 turns,\npreventing escape.");
const u8 gMoveDescription_ColdSnap[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_MuddyWater[] = _("30%: -1 Accuracy.");
const u8 gMoveDescription_BulletSeed[] = _("Hits 2-5 times.");
const u8 gMoveDescription_BladeFlash[] = _("+1 Priority.");
const u8 gMoveDescription_IceShard[] = _("+1 Priority.");
const u8 gMoveDescription_IronDefense[] = _("+2 Defense.");
const u8 gMoveDescription_Block[] = _("Traps the foe,\npreventing escape.");
const u8 gMoveDescription_Howl[] = _("+1 Attack.");
const u8 gMoveDescription_HeatClaw[] = _("Has Power equal to\nthe foe's Cost.");
const u8 gMoveDescription_LeafStorm[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_BulkUp[] = _("+1 Attack.\n+1 Defense.");
const u8 gMoveDescription_Bounce[] = _("A 2-turn attack.\nThe user avoids\nharm between turns\nby bouncing high.");
const u8 gMoveDescription_MudShot[] = _("30%: -1 Speed.");
const u8 gMoveDescription_PoisonJab[] = _("30%: Poison foe.");
const u8 gMoveDescription_Covet[] = _("Steals the foe's\nheld item, if not\ncurrently holding\nanything.");
const u8 gMoveDescription_VoltTackle[] = _("10%: Paralyze foe.\nUser takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_MagicalLeaf[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_Splashback[] = _("-4 Priority.\nPower doubles if\nuser was hurt by\nan attack.");
const u8 gMoveDescription_CalmMind[] = _("+1 Sp. Atk.\n+1 Sp. Def.");
const u8 gMoveDescription_LeafBlade[] = _("High critical rate.");
const u8 gMoveDescription_DragonDance[] = _("+1 Attack.\n+1 Speed.");
const u8 gMoveDescription_RockBlast[] = _("Hits 2-5 times.");
const u8 gMoveDescription_ShockWave[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_WaterPulse[] = _("30%: Confuse foe.");
const u8 gMoveDescription_Apollon[] = _("Hits 2 turns later.\nDamage is equal to\n1.5 times the\nuser's level.");
const u8 gMoveDescription_PsychoBoost[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_DrainPunch[] = _("User recovers half\nthe damage dealt.");
const u8 gMoveDescription_AuraSphere[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_FocusBlast[] = _("10%: -1 Sp. Def.");
const u8 gMoveDescription_HeartBreak[] = _("Is strong against\nHeart-types.");
const u8 gMoveDescription_Decision[] = _("Won't miss unless\nentirely unable to\nhit the foe.");
const u8 gMoveDescription_RapidFire[] = _("+1 Priority.");
const u8 gMoveDescription_HeadSmash[] = _("User takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_SeedBomb[] = _("A plain attack.");
const u8 gMoveDescription_FreezeDry[] = _("Is strong against\nWater-types.");
const u8 gMoveDescription_HoneClaws[] = _("+1 Attack.\n+1 Accuracy.");
const u8 gMoveDescription_QuiverDance[] = _("+1 Sp. Atk.\n+1 Sp. Def.\n+1 Speed.");
const u8 gMoveDescription_ShellSmash[] = _("+2 Attack, Sp. Atk,\nand Speed.\n-1 Own Defense, Own\nSp. Def.");
const u8 gMoveDescription_CloseCombat[] = _("-1 Own Defense.\n-1 Own Sp. Def.");
const u8 gMoveDescription_DarkVoid[] = _("Inflicts sleep.");
const u8 gMoveDescription_TrickRoom[] = _("-7 Priority.\nFor 5 turns, slower\npuppets move before\nfaster puppets.");
const u8 gMoveDescription_Tailwind[] = _("For 4 turns, allies\nhave doubled Speed.");
const u8 gMoveDescription_UTurn[] = _("User switches out.");
const u8 gMoveDescription_VoltSwitch[] = _("User switches out.");
const u8 gMoveDescription_Purify[] = _("The target's type\nbecomes Normal.");
const u8 gMoveDescription_Horsepower[] = _("A plain attack.");
const u8 gMoveDescription_HealingWish[] = _("The user faints.\nThe next puppet\nrecovers all HP\nand status.");
const u8 gMoveDescription_Gale[] = _("+1 Priority.");
const u8 gMoveDescription_AbyssNova[] = _("The user faints.");
const u8 gMoveDescription_Mishaguji[] = _("100%: Curses foe.");
const u8 gMoveDescription_AegisMerge[] = _("+3 Defense, Sp. Def\nRestores 1/16 HP\neach turn, but\nforbids switching.");
const u8 gMoveDescription_Exterminate[] = _("Bypasses Abilities.");
const u8 gMoveDescription_OblivionWing[] = _("User recovers 75%\nof the damage\ndealt.");
const u8 gMoveDescription_FireFang[] = _("10%: Burn foe.\n10%: Foe flinches.");
const u8 gMoveDescription_IceFang[] = _("10%: Freeze foe.\n10%: Foe flinches.");
const u8 gMoveDescription_ThunderFang[] = _("10%: Paralyze foe.\n10%: Foe flinches.");
const u8 gMoveDescription_Acupressure[] = _("+2 Random stat");
const u8 gMoveDescription_WildHunt[] = _("User takes recoil\nequal to 33% of\ndamage dealt.");
const u8 gMoveDescription_Manashock[] = _("Hits the foe's\nDefense instead of\ntheir Sp. Def.");
const u8 gMoveDescription_FlameCharge[] = _("100%: +1 Speed");
const u8 gMoveDescription_ChargeBeam[] = _("70%: +1 Sp. Atk");
const u8 gMoveDescription_PsychoShift[] = _("Transfers a status\nproblem from the\nuser to the foe.");
const u8 gMoveDescription_Bestow[] = _("Transfers a held\nitem from the user\nto the foe.");
const u8 gMoveDescription_Hex[] = _("Doubles in power if\nfoe has a status\nproblem.");
const u8 gMoveDescription_PowerWhip[] = _("A plain attack.");
const u8 gMoveDescription_HammerArm[] = _("100%: -1 Own Speed.");
const u8 gMoveDescription_BoltStrike[] = _("10%: Paralyze foe.");
const u8 gMoveDescription_AnchorShot[] = _("A plain attack.");
const u8 gMoveDescription_Sutra[] = _("A plain attack.");
const u8 gMoveDescription_PristineShot[] = _("Won't randomly miss.\nBypasses Detect.\nBypasses Abilities.");
const u8 gMoveDescription_Destitution[] = _("Ensnares the foe\nfor 4-5 turns,\npreventing escape.");
const u8 gMoveDescription_EarthPress[] = _("Uses the Defense\nstat instead of\nthe Attack stat.");
const u8 gMoveDescription_HappyHour[] = _("Doubles the prize\nmoney from winning\nthe battle.");
const u8 gMoveDescription_HoldHands[] = _("??????????");
const u8 gMoveDescription_BallLightning[] = _("High critical rate.\n10%: Paralyze foe.");
const u8 gMoveDescription_MoodSwing[] = _("+1 Random Stat");
const u8 gMoveDescription_AlphaStrike[] = _("+2 Priority.\nOnly usable on\nthe first turn.");
const u8 gMoveDescription_LunarSea[] = _("User takes recoil\nequal to 50% of\nown max HP.");
const u8 gMoveDescription_Apotheosis[] = _("+1 Sp. Atk.\n+1 Sp. Def.\n+1 Accuracy.\n+1 Evasion.");
const u8 gMoveDescription_Identify[] = _("+1 Priority.\nLearns foe moves,\nAbility, and\nheld item.");
const u8 gMoveDescription_CorpseBlaze[] = _("If target faints,\ngain +3 Sp. Atk.");
const u8 gMoveDescription_GroupPrank[] = _("A 2-turn attack.\nHits twice.\nDamage is half of\nfoe's current HP.");
const u8 gMoveDescription_Scald[] = _("30%: Burn foe.");
const u8 gMoveDescription_CircleThrow[] = _("Forces foe switch.\nIn the wild, ends\nthe fight outright.");
const u8 gMoveDescription_ClearSmog[] = _("Resets all stat\nchanges back to +0\nfor the target.");
const u8 gMoveDescription_Butchery[] = _("User takes 2x\ndamage and won't\navoid moves until\nusing another move.");
const u8 gMoveDescription_BeddyBye[] = _("Restores all HP,\nbut the user falls\nasleep for 2 turns.\nUser switches out.");
const u8 gMoveDescription_Punishment[] = _("Gains 20 power\nfor each stat\nboost on the\nfoe.");
const u8 gMoveDescription_Shriek[] = _("30%: Foe flinches.");
const u8 gMoveDescription_Flight[] = _("Sets user's Ability\nto Levitate, letting\nthem avoid Earth\nmoves.");
const u8 gMoveDescription_CoreSurge[] = _("If used by Tensoku,\nswitches its form.");
const u8 gMoveDescription_Cataclysm[] = _("A 2-turn attack.\n80%: Foe flinches.\nHigh critical rate.");
const u8 gMoveDescription_Blossoming[] = _("50%: +1 Attack.\n50%: +1 Sp. Atk.");
const u8 gMoveDescription_SpatialRend[] = _("High critical rate.");
const u8 gMoveDescription_PassionDance[] = _("Attacks blindly for\n2-3 turns, then\nconfuses the user.");
const u8 gMoveDescription_TakeOver[] = _("Uses the foe's\nSp. Atk stat instead\nof the user's.");
const u8 gMoveDescription_ThirdEye[] = _("User learns the last\nmove the foe used\npermanently, but\nforgets all others.");
const u8 gMoveDescription_DemonBook[] = _("User uses a 70-80\npower physical move\nthat is effective\non the target.");
const u8 gMoveDescription_DrillPeck[] = _("HOLY SHIT\nITS DRILL PECK");
const u8 gMoveDescription_MeFirst[] = _("Uses the move the\nfoe is about to\nuse, and with 50%\nmore power.");
const u8 gMoveDescription_AnoxicFumes[] = _("-2 Own Sp. Atk.");
const u8 gMoveDescription_Dummy[] = _("lol");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_FEINT         - 1] = gMoveDescription_Feint,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_NIGHT_SLASH   - 1] = gMoveDescription_NightSlash,
    [MOVE_JUDGMENT      - 1] = gMoveDescription_Judgment,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_BRAVER        - 1] = gMoveDescription_Braver,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_KNIFE_THROW   - 1] = gMoveDescription_KnifeThrow,
    [MOVE_MAGIC_KNIFE   - 1] = gMoveDescription_MagicKnife,
    [MOVE_SCULPTURE     - 1] = gMoveDescription_Sculpture,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_SEAL_NEEDLE   - 1] = gMoveDescription_SealNeedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_JAMMING       - 1] = gMoveDescription_Jamming,
    [MOVE_SONICBOOM     - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_POISON_TEARS  - 1] = gMoveDescription_PoisonTears,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLEBEAM    - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_FOUL_PLAY     - 1] = gMoveDescription_FoulPlay,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_SKANDAS_LEG   - 1] = gMoveDescription_SkandasLeg,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_STORM   - 1] = gMoveDescription_PetalStorm,
    [MOVE_MESMERISM     - 1] = gMoveDescription_Mesmerism,
    [MOVE_DARK_PULSE    - 1] = gMoveDescription_DarkPulse,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDERSHOCK  - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_WRECKER  - 1] = gMoveDescription_RockWrecker,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_PSYSHOT       - 1] = gMoveDescription_Psyshot,
    [MOVE_MANA_BURST    - 1] = gMoveDescription_ManaBurst,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_ZEN_HEADBUTT  - 1] = gMoveDescription_ZenHeadbutt,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_WORK_UP       - 1] = gMoveDescription_WorkUp,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_DEBT_SPIRAL   - 1] = gMoveDescription_DebtSpiral,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_MIND_BOMB     - 1] = gMoveDescription_MindBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_GUNK_SHOT     - 1] = gMoveDescription_GunkShot,
    [MOVE_WOOD_HAMMER   - 1] = gMoveDescription_WoodHammer,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_MANA_SHIELD   - 1] = gMoveDescription_ManaShield,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_DANMAKU       - 1] = gMoveDescription_Danmaku,
    [MOVE_TOPSY_TURVY   - 1] = gMoveDescription_TopsyTurvy,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_LUNA_DIAL     - 1] = gMoveDescription_LunaDial,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_DAUNT         - 1] = gMoveDescription_Daunt,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_OMINOUS_WIND  - 1] = gMoveDescription_OminousWind,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_BURN_POWDER   - 1] = gMoveDescription_BurnPowder,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_DISPERSE      - 1] = gMoveDescription_Disperse,
    [MOVE_AQUA_JET      - 1] = gMoveDescription_AquaJet,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_SUCKER_PUNCH  - 1] = gMoveDescription_SuckerPunch,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_KILLING_BITE  - 1] = gMoveDescription_KillingBite,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_GIGA_IMPACT   - 1] = gMoveDescription_GigaImpact,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_SHADOW_SNEAK  - 1] = gMoveDescription_ShadowSneak,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_HEARTS_EYE    - 1] = gMoveDescription_HeartsEye,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FEINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_POISON_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_BLACK_RIPPLE  - 1] = gMoveDescription_BlackRipple,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_DISCHARGE     - 1] = gMoveDescription_Discharge,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_HEAD_RUSH     - 1] = gMoveDescription_HeadRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_SMILE         - 1] = gMoveDescription_Charm,
    [MOVE_TREMORS       - 1] = gMoveDescription_Tremors,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_HOSPITALITY   - 1] = gMoveDescription_Hospitality,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_LURE_OF_DEATH - 1] = gMoveDescription_LureOfDeath,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_FINAL_GAMBIT  - 1] = gMoveDescription_FinalGambit,
    [MOVE_PRANK         - 1] = gMoveDescription_Prank,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_BRAVE_BIRD    - 1] = gMoveDescription_BraveBird,
    [MOVE_LAVA_PLUME    - 1] = gMoveDescription_LavaPlume,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_STEEL_FIST    - 1] = gMoveDescription_SteelFist,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_ENERGY_LIGHT  - 1] = gMoveDescription_EnergyLight,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_LUNATIC       - 1] = gMoveDescription_LUNATIC,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_SHOCK_SPIN    - 1] = gMoveDescription_ShockSpin,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_PSYCHO_CUT    - 1] = gMoveDescription_PsychoCut,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_DRAWN_LINE    - 1] = gMoveDescription_DrawnLine,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_PERFORMANCE   - 1] = gMoveDescription_Performance,
    [MOVE_NASTY_PLOT    - 1] = gMoveDescription_NastyPlot,
    [MOVE_MIRROR_SHOT   - 1] = gMoveDescription_MirrorShot,
    [MOVE_AQUA_RING     - 1] = gMoveDescription_AquaRing,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_LUCKY_CHANT   - 1] = gMoveDescription_LuckyChant,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_COPYCAT       - 1] = gMoveDescription_Copycat,
    [MOVE_ROCK_BULLET   - 1] = gMoveDescription_RockBullet,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_RECOLLECTION  - 1] = gMoveDescription_Recollection,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_SHADOW_DANCE  - 1] = gMoveDescription_ShadowDance,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_SHADOW_FORCE  - 1] = gMoveDescription_ShadowForce,
    [MOVE_FORCE_PALM    - 1] = gMoveDescription_ForcePalm,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_MANA_CHARGE   - 1] = gMoveDescription_ManaCharge,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_ROOST         - 1] = gMoveDescription_Roost,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_EARTH_POWER   - 1] = gMoveDescription_EarthPower,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_CROSS_POISON  - 1] = gMoveDescription_CrossPoison,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_FLARE_BLITZ   - 1] = gMoveDescription_FlareBlitz,
    [MOVE_DAM_BREACH    - 1] = gMoveDescription_DamBreach,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_SLASH     - 1] = gMoveDescription_AirSlash,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_SHADOW_HIT    - 1] = gMoveDescription_ShadowHit,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_BINDING_VOICE - 1] = gMoveDescription_BindingVoice,
    [MOVE_NATURE_SOUND  - 1] = gMoveDescription_NatureSound,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_DRACO_METEOR  - 1] = gMoveDescription_DracoMeteor,
    [MOVE_AQUA_SHOWER   - 1] = gMoveDescription_AquaShower,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SOAR          - 1] = gMoveDescription_Soar,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_COLD_SNAP     - 1] = gMoveDescription_ColdSnap,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_BLADE_FLASH   - 1] = gMoveDescription_BladeFlash,
    [MOVE_ICE_SHARD     - 1] = gMoveDescription_IceShard,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_HEAT_CLAW     - 1] = gMoveDescription_HeatClaw,
    [MOVE_LEAF_STORM    - 1] = gMoveDescription_LeafStorm,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_JAB    - 1] = gMoveDescription_PoisonJab,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_SPLASHBACK    - 1] = gMoveDescription_Splashback,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_GALE_DANCE    - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_APOLLON       - 1] = gMoveDescription_Apollon,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
    [MOVE_DRAIN_PUNCH   - 1] = gMoveDescription_DrainPunch,
    [MOVE_AURA_SPHERE   - 1] = gMoveDescription_AuraSphere,
    [MOVE_FOCUS_BLAST   - 1] = gMoveDescription_FocusBlast,
    [MOVE_HEART_BREAK   - 1] = gMoveDescription_HeartBreak,
    [MOVE_DECISION      - 1] = gMoveDescription_Decision,
    [MOVE_RAPID_FIRE    - 1] = gMoveDescription_RapidFire,
    [MOVE_HEAD_SMASH    - 1] = gMoveDescription_HeadSmash,
    [MOVE_SEED_BOMB     - 1] = gMoveDescription_SeedBomb,
    [MOVE_FREEZE_DRY    - 1] = gMoveDescription_FreezeDry,
    [MOVE_HONE_CLAWS    - 1] = gMoveDescription_HoneClaws,
    [MOVE_QUIVER_DANCE  - 1] = gMoveDescription_QuiverDance,
    [MOVE_SHELL_SMASH   - 1] = gMoveDescription_ShellSmash,
    [MOVE_CLOSE_COMBAT  - 1] = gMoveDescription_CloseCombat,
    [MOVE_DARK_VOID     - 1] = gMoveDescription_DarkVoid,
    [MOVE_TRICK_ROOM    - 1] = gMoveDescription_TrickRoom,
    [MOVE_TAILWIND      - 1] = gMoveDescription_Tailwind,
    [MOVE_U_TURN        - 1] = gMoveDescription_UTurn,
    [MOVE_VOLT_SWITCH   - 1] = gMoveDescription_VoltSwitch,
    [MOVE_PURIFY        - 1] = gMoveDescription_Purify,
    [MOVE_HORSEPOWER    - 1] = gMoveDescription_Horsepower,
    [MOVE_HEALING_WISH  - 1] = gMoveDescription_HealingWish,
    [MOVE_GALE          - 1] = gMoveDescription_Gale,
    [MOVE_ABYSS_NOVA    - 1] = gMoveDescription_AbyssNova,
    [MOVE_MISHAGUJI     - 1] = gMoveDescription_Mishaguji,
    [MOVE_AEGIS_MERGE   - 1] = gMoveDescription_AegisMerge,
    [MOVE_EXTERMINATE   - 1] = gMoveDescription_Exterminate,
    [MOVE_OBLIVION_WING - 1] = gMoveDescription_OblivionWing,
    [MOVE_FIRE_FANG     - 1] = gMoveDescription_FireFang,
    [MOVE_ICE_FANG      - 1] = gMoveDescription_IceFang,
    [MOVE_THUNDER_FANG  - 1] = gMoveDescription_ThunderFang,
    [MOVE_ACUPRESSURE   - 1] = gMoveDescription_Acupressure,
    [MOVE_WILD_HUNT     - 1] = gMoveDescription_WildHunt,
    [MOVE_MANASHOCK     - 1] = gMoveDescription_Manashock,
    [MOVE_FLAME_CHARGE  - 1] = gMoveDescription_FlameCharge,
    [MOVE_CHARGE_BEAM   - 1] = gMoveDescription_ChargeBeam,
    [MOVE_PSYCHO_SHIFT  - 1] = gMoveDescription_PsychoShift,
    [MOVE_BESTOW        - 1] = gMoveDescription_Bestow,
    [MOVE_HEX           - 1] = gMoveDescription_Hex,
    [MOVE_POWER_WHIP    - 1] = gMoveDescription_PowerWhip,
    [MOVE_HAMMER_ARM    - 1] = gMoveDescription_HammerArm,
    [MOVE_BOLT_STRIKE   - 1] = gMoveDescription_BoltStrike,
    [MOVE_ANCHOR_SHOT   - 1] = gMoveDescription_AnchorShot,
    [MOVE_SUTRA         - 1] = gMoveDescription_Sutra,
    [MOVE_PRISTINE_SHOT - 1] = gMoveDescription_PristineShot,
    [MOVE_DESTITUTION   - 1] = gMoveDescription_Destitution,
    [MOVE_EARTH_PRESS   - 1] = gMoveDescription_EarthPress,
    [MOVE_HAPPY_HOUR    - 1] = gMoveDescription_HappyHour,
    [MOVE_HOLD_HANDS    - 1] = gMoveDescription_HoldHands,
    [MOVE_BALL_LIGHTNING- 1] = gMoveDescription_BallLightning,
    [MOVE_MOOD_SWING    - 1] = gMoveDescription_MoodSwing,
    [MOVE_ALPHA_STRIKE  - 1] = gMoveDescription_AlphaStrike,
    [MOVE_LUNAR_SEA     - 1] = gMoveDescription_LunarSea,
    [MOVE_APOTHEOSIS    - 1] = gMoveDescription_Apotheosis,
    [MOVE_IDENTIFY      - 1] = gMoveDescription_Identify,
    [MOVE_CORPSE_BLAZE  - 1] = gMoveDescription_CorpseBlaze,
    [MOVE_GROUP_PRANK   - 1] = gMoveDescription_GroupPrank,
	[MOVE_SCALD         - 1] = gMoveDescription_Scald,
    [MOVE_CIRCLE_THROW  - 1] = gMoveDescription_CircleThrow,
    [MOVE_CLEAR_SMOG    - 1] = gMoveDescription_ClearSmog,
    [MOVE_BUTCHERY      - 1] = gMoveDescription_Butchery,
    [MOVE_BEDDY_BYE     - 1] = gMoveDescription_BeddyBye,
    [MOVE_SNAP_TRAP     - 1] = gMoveDescription_Wrap,
    [MOVE_PUNISHMENT    - 1] = gMoveDescription_Punishment,
	[MOVE_SHRIEK        - 1] = gMoveDescription_Shriek,
	[MOVE_FLIGHT        - 1] = gMoveDescription_Flight,
	[MOVE_CORE_SURGE    - 1] = gMoveDescription_CoreSurge,
	[MOVE_CATACLYSM     - 1] = gMoveDescription_Cataclysm,
	[MOVE_BLOSSOMING    - 1] = gMoveDescription_Blossoming,
	[MOVE_SPATIAL_REND  - 1] = gMoveDescription_SpatialRend,
	[MOVE_PASSION_DANCE - 1] = gMoveDescription_PassionDance,
	[MOVE_TAKE_OVER     - 1] = gMoveDescription_TakeOver,
	[MOVE_THIRD_EYE     - 1] = gMoveDescription_ThirdEye,
	[MOVE_DEMON_BOOK    - 1] = gMoveDescription_DemonBook,
	[MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_ME_FIRST      - 1] = gMoveDescription_MeFirst,
	[MOVE_ANOXIC_FUMES  - 1] = gMoveDescription_AnoxicFumes,
};