#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("A physical attack\ndelivered with a\nlong tail or a\nforeleg, etc.");
const u8 gMoveDescription_KarateChop[] = _("The foe is attacked\nwith a sharp chop.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_DoubleSlap[] = _("The foe is slapped\nrepeatedly, back\nand forth, two to\nfive times.");
const u8 gMoveDescription_CometPunch[] = _("The foe is hit with\na flurry of punches\nthat strike two to\nfive times.");
const u8 gMoveDescription_MegaPunch[] = _("The foe is slugged\nby a punch thrown\nwith muscle-packed\npower.");
const u8 gMoveDescription_PayDay[] = _("Numerous coins are\nhurled at the foe.\nMoney is earned\nafter battle.");
const u8 gMoveDescription_FirePunch[] = _("The foe is punched\nwith a fiery fist.\nIt may leave the\nfoe with a burn.");
const u8 gMoveDescription_IcePunch[] = _("The foe is punched\nwith an icy fist.\nIt may leave the\nfoe frozen.");
const u8 gMoveDescription_ThunderPunch[] = _("The foe is punched\nwith an electrified\nfist. It may leave\nthe foe paralyzed.");
const u8 gMoveDescription_Scratch[] = _("Hard, pointed, and\nsharp claws rake\nthe foe.");
const u8 gMoveDescription_ViceGrip[] = _("Huge, impressive\npincers grip and\nsqueeze the foe.");
const u8 gMoveDescription_Guillotine[] = _("A vicious tearing\nattack with pincers.\nThe foe will faint\nif it hits.");
const u8 gMoveDescription_RazorWind[] = _("Blades of wind hit\nthe foe on the 2nd\nturn. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SwordsDance[] = _("A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.");
const u8 gMoveDescription_Cut[] = _("A basic attack.\nIt can be used to\ncut down thin trees\nand grass.");
const u8 gMoveDescription_Gust[] = _("Strikes the foe\nwith a gust of wind\nwhipped up by\nwings.");
const u8 gMoveDescription_WingAttack[] = _("The foe is struck\nwith large, imposing\nwings spread wide.");
const u8 gMoveDescription_Whirlwind[] = _("The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.");
const u8 gMoveDescription_Fly[] = _("A 2-turn move that\nhits on the 2nd\nturn. Use it to fly\nto any known town.");
const u8 gMoveDescription_Bind[] = _("A long body or\ntentacles are used\nto bind the foe for\ntwo to five turns.");
const u8 gMoveDescription_Slam[] = _("The foe is struck\nwith a long tail,\nvines, etc.");
const u8 gMoveDescription_VineWhip[] = _("The foe is struck\nwith slender, whip-\nlike vines.");
const u8 gMoveDescription_Stomp[] = _("The foe is stomped\nwith a big foot.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_DoubleKick[] = _("Two legs are used\nto quickly kick the\nfoe twice in one\nturn.");
const u8 gMoveDescription_MegaKick[] = _("The foe is attacked\nby a kick fired\nwith muscle-packed\npower.");
const u8 gMoveDescription_JumpKick[] = _("The user jumps up\nhigh, then kicks.\nIf it misses, the\nuser hurts itself.");
const u8 gMoveDescription_RollingKick[] = _("A quick kick from a\nrolling spin.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_SandAttack[] = _("A lot of sand is\nhurled in the foe's\nface, reducing its\naccuracy.");
const u8 gMoveDescription_Headbutt[] = _("The user sticks its\nhead out and rams.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_HornAttack[] = _("The foe is jabbed\nwith a sharply\npointed horn to\ninflict damage.");
const u8 gMoveDescription_FuryAttack[] = _("The foe is jabbed\nrepeatedly with a\nhorn or beak two to\nfive times.");
const u8 gMoveDescription_HornDrill[] = _("The horn is rotated\nlike a drill to ram.\nThe foe will faint\nif it hits.");
const u8 gMoveDescription_Tackle[] = _("A physical attack\nin which the user\ncharges, full body,\ninto the foe.");
const u8 gMoveDescription_BodySlam[] = _("The user drops its\nfull body on the\nfoe. It may leave\nthe foe paralyzed.");
const u8 gMoveDescription_Wrap[] = _("A long body or\nvines are used to\nwrap the foe for\ntwo to five turns.");
const u8 gMoveDescription_TakeDown[] = _("A reckless, full-\nbody charge attack\nthat also hurts the\nuser a little.");
const u8 gMoveDescription_Thrash[] = _("The user rampages\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_DoubleEdge[] = _("A reckless, life-\nrisking tackle that\nalso hurts the user\na little.");
const u8 gMoveDescription_TailWhip[] = _("The user wags its\ntail cutely, making\nthe foe lower its\nDEFENSE stat.");
const u8 gMoveDescription_PoisonSting[] = _("The foe is stabbed\nwith a toxic barb,\netc. It may poison\nthe foe.");
const u8 gMoveDescription_Twineedle[] = _("The foe is stabbed\ntwice with foreleg\nstingers. It may\npoison the foe.");
const u8 gMoveDescription_PinMissile[] = _("Sharp pins are shot\nat the foe and hit\ntwo to five times\nat once.");
const u8 gMoveDescription_Leer[] = _("The foe is given an\nintimidating look\nthat lowers its\nDEFENSE stat.");
const u8 gMoveDescription_Bite[] = _("The user bites with\nvicious fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_Growl[] = _("The user growls in\na cute way, making\nthe foe lower its\nATTACK stat.");
const u8 gMoveDescription_Roar[] = _("The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.");
const u8 gMoveDescription_Sing[] = _("A soothing song\nin a calming voice\nlulls the foe into\na deep slumber.");
const u8 gMoveDescription_Supersonic[] = _("The user generates\nodd sound waves.\nIt may confuse the\nfoe.");
const u8 gMoveDescription_SonicBoom[] = _("The foe is hit with\na shock wave that\nalways inflicts 20-\nHP damage.");
const u8 gMoveDescription_Disable[] = _("For a few turns,\nit prevents the foe\nfrom using the move\nit last used.");
const u8 gMoveDescription_Acid[] = _("The foe is sprayed\nwith a harsh, hide-\nmelting acid that\nmay lower DEFENSE.");
const u8 gMoveDescription_Ember[] = _("The foe is attacked\nwith small flames.\nThe foe may suffer\na burn.");
const u8 gMoveDescription_Flamethrower[] = _("The foe is scorched\nwith intense flames.\nThe foe may suffer\na burn.");
const u8 gMoveDescription_Mist[] = _("The ally party is\nprotected by a\nmist that prevents\nstat reductions.");
const u8 gMoveDescription_WaterGun[] = _("The foe is struck\nwith a lot of water\nexpelled forcibly\nfrom the mouth.");
const u8 gMoveDescription_HydroPump[] = _("A high volume of\nwater is blasted at\nthe foe under great\npressure.");
const u8 gMoveDescription_Surf[] = _("A big wave crashes\ndown on the foe.\nCan also be used\nfor crossing water.");
const u8 gMoveDescription_IceBeam[] = _("The foe is struck\nwith an icy beam.\nIt may freeze the\nfoe solid.");
const u8 gMoveDescription_Blizzard[] = _("The foe is blasted\nwith a blizzard.\nIt may freeze the\nfoe solid.");
const u8 gMoveDescription_Psybeam[] = _("A peculiar ray is\nshot at the foe.\nIt may leave the\nfoe confused.");
const u8 gMoveDescription_BubbleBeam[] = _("A spray of bubbles\nstrikes the foe.\nIt may lower the\nfoe's SPEED stat.");
const u8 gMoveDescription_AuroraBeam[] = _("A rainbow-colored\nattack beam.\nIt may lower the\nfoe's ATTACK stat.");
const u8 gMoveDescription_HyperBeam[] = _("A severely damaging\nattack that makes\nthe user rest on\nthe next turn.");
const u8 gMoveDescription_Peck[] = _("The foe is jabbed\nwith a sharply\npointed beak or\nhorn.");
const u8 gMoveDescription_DrillPeck[] = _("A corkscrewing\nattack with the\nsharp beak acting\nas a drill.");
const u8 gMoveDescription_Submission[] = _("A reckless, full-\nbody throw attack\nthat also hurts the\nuser a little.");
const u8 gMoveDescription_LowKick[] = _("A low, tripping kick\nthat inflicts more\ndamage on heavier\nfoes.");
const u8 gMoveDescription_Counter[] = _("A retaliation move\nthat counters any\nphysical hit with\ndouble the damage.");
const u8 gMoveDescription_SeismicToss[] = _("A gravity-fed throw\nthat causes damage\nmatching the user's\nlevel.");
const u8 gMoveDescription_Strength[] = _("The foe is slugged\nat maximum power.\nCan also be used\nto move boulders.");
const u8 gMoveDescription_Absorb[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_MegaDrain[] = _("A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LeechSeed[] = _("A seed is planted\non the foe to steal\nsome HP for the \nuser on every turn.");
const u8 gMoveDescription_Growth[] = _("The user's body is\nforced to grow,\nraising the SP.\nATK stat.");
const u8 gMoveDescription_RazorLeaf[] = _("The foe is hit with\na cutting leaf.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SolarBeam[] = _("A 2-turn move that\nblasts the foe with\nabsorbed energy in\nthe 2nd turn.");
const u8 gMoveDescription_PoisonPowder[] = _("A cloud of toxic\ndust is scattered.\nIt may poison the\nfoe.");
const u8 gMoveDescription_StunSpore[] = _("Paralyzing dust is\nscattered wildly.\nIt may paralyze\nthe foe.");
const u8 gMoveDescription_SleepPowder[] = _("A sleep-inducing\ndust is scattered\nin high volume\naround a foe.");
const u8 gMoveDescription_PetalDance[] = _("The user attacks\nwith petals for two\nto three turns,\nthen gets confused.");
const u8 gMoveDescription_StringShot[] = _("The foe is bound\nwith strings shot\nfrom the mouth to\nreduce its SPEED.");
const u8 gMoveDescription_DragonRage[] = _("The foe is hit with\na shock wave that\nalways inflicts 40-\nHP damage.");
const u8 gMoveDescription_FireSpin[] = _("The foe is trapped\nin an intense spiral\nof fire that rages\ntwo to five turns.");
const u8 gMoveDescription_ThunderShock[] = _("An electric shock\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_Thunderbolt[] = _("A strong electrical\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_ThunderWave[] = _("A weak electric\nshock that is sure\nto cause paralysis\nif it hits.");
const u8 gMoveDescription_Thunder[] = _("A brutal lightning\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_RockThrow[] = _("The foe is attacked\nwith a shower of\nsmall, easily\nthrown rocks.");
const u8 gMoveDescription_Earthquake[] = _("An earthquake that\nstrikes all POKéMON\nin battle excluding\nthe user.");
const u8 gMoveDescription_Fissure[] = _("The foe is dropped\ninto a fissure.\nThe foe faints if it\nhits.");
const u8 gMoveDescription_Dig[] = _("An attack that hits\non the 2nd turn.\nCan also be used\nto exit dungeons.");
const u8 gMoveDescription_Toxic[] = _("A move that badly\npoisons the foe.\nIts poison damage\nworsens every turn.");
const u8 gMoveDescription_Confusion[] = _("A weak telekinetic\nattack that may\nalso leave the foe\nconfused.");
const u8 gMoveDescription_Psychic[] = _("A strong telekinetic\nattack. It may also\nlower the foe's\nSP. DEF stat.");
const u8 gMoveDescription_Hypnosis[] = _("Hypnotic suggestion\nis used to make the\nfoe fall into a\ndeep sleep.");
const u8 gMoveDescription_Meditate[] = _("The user meditates\nto awaken its power\nand raise its\nATTACK stat.");
const u8 gMoveDescription_Agility[] = _("The user relaxes\nand lightens its\nbody to sharply\nboost its SPEED.");
const u8 gMoveDescription_QuickAttack[] = _("An almost invisibly\nfast attack that\nis certain to strike\nfirst.");
const u8 gMoveDescription_Rage[] = _("An attack that\nbecomes stronger\neach time the user\nis hit in battle.");
const u8 gMoveDescription_Teleport[] = _("Use it to flee from\nany wild POKéMON.\nAlso warps to the\nlast POKé CENTER.");
const u8 gMoveDescription_NightShade[] = _("An attack with a\nmirage that inflicts\ndamage matching\nthe user's level.");
const u8 gMoveDescription_Mimic[] = _("The user copies the\nmove last used by\nthe foe for the\nrest of the battle.");
const u8 gMoveDescription_Screech[] = _("An ear-splitting\nscreech is emitted\nto sharply reduce\nthe foe's DEFENSE.");
const u8 gMoveDescription_DoubleTeam[] = _("The user creates\nillusory copies of\nitself to raise its\nevasiveness.");
const u8 gMoveDescription_Recover[] = _("A self-healing move\nthat restores HP by\nup to half of the\nuser's maximum HP.");
const u8 gMoveDescription_Harden[] = _("The user stiffens\nall the muscles in\nits body to raise\nits DEFENSE stat.");
const u8 gMoveDescription_Minimize[] = _("The user compresses\nall the cells in its\nbody to raise its\nevasiveness.");
const u8 gMoveDescription_Smokescreen[] = _("An obscuring cloud\nof smoke or ink\nreduces the foe's\naccuracy.");
const u8 gMoveDescription_ConfuseRay[] = _("The foe is exposed\nto a sinister ray\nthat triggers\nconfusion.");
const u8 gMoveDescription_Withdraw[] = _("The user withdraws\nits body in its hard\nshell, raising its\nDEFENSE stat.");
const u8 gMoveDescription_DefenseCurl[] = _("The user curls up\nto conceal weak\nspots and raise its\nDEFENSE stat.");
const u8 gMoveDescription_Barrier[] = _("The user creates a\nsturdy wall that\nsharply raises its\nDEFENSE stat.");
const u8 gMoveDescription_LightScreen[] = _("A wall of light\ncuts damage from\nSP. ATK attacks\nfor five turns.");
const u8 gMoveDescription_Haze[] = _("Eliminates all stat\nchanges among all\nPOKéMON engaged in\nbattle.");
const u8 gMoveDescription_Reflect[] = _("A wall of light\ncuts damage from\nphysical attacks\nfor five turns.");
const u8 gMoveDescription_FocusEnergy[] = _("The user takes a\ndeep breath and\nfocuses to raise its\ncritical-hit ratio.");
const u8 gMoveDescription_Bide[] = _("The user endures\nattacks for two\nturns, then strikes\nback double.");
const u8 gMoveDescription_Metronome[] = _("Waggles a finger\nand stimulates the\nbrain into using any\nmove at random.");
const u8 gMoveDescription_MirrorMove[] = _("The user counters\nthe move last used\nby the foe with the\nsame move.");
const u8 gMoveDescription_SelfDestruct[] = _("The user blows up\nto inflict severe\ndamage, even\nmaking itself faint.");
const u8 gMoveDescription_EggBomb[] = _("A large egg is\nhurled with great\nforce at the foe to\ninflict damage.");
const u8 gMoveDescription_Lick[] = _("The foe is licked\nand hit with a long\ntongue. It may\nalso paralyze.");
const u8 gMoveDescription_Smog[] = _("The foe is attacked\nwith exhaust gases.\nIt may also poison\nthe foe.");
const u8 gMoveDescription_Sludge[] = _("Toxic sludge is\nhurled at the foe.\nIt may poison the\ntarget.");
const u8 gMoveDescription_BoneClub[] = _("The foe is clubbed\nwith a bone held in\nhand. It may make\nthe foe flinch.");
const u8 gMoveDescription_FireBlast[] = _("The foe is hit with\nan intense flame.\nIt may leave the\ntarget with a burn.");
const u8 gMoveDescription_Waterfall[] = _("A powerful charge\nattack. It can also\nbe used to climb\na waterfall.");
const u8 gMoveDescription_Clamp[] = _("The foe is clamped\nand squeezed by\nthe user's shell for\ntwo to five turns.");
const u8 gMoveDescription_Swift[] = _("Star-shaped rays\nthat never miss are\nfired at all foes in\nbattle.");
const u8 gMoveDescription_SkullBash[] = _("The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.");
const u8 gMoveDescription_SpikeCannon[] = _("Sharp spikes are\nfired at the foe to\nstrike two to five\ntimes.");
const u8 gMoveDescription_Constrict[] = _("The foe is attacked\nwith long tentacles\nor vines. It may\nlower SPEED.");
const u8 gMoveDescription_Amnesia[] = _("Forgets about\nsomething and\nsharply raises\nSP. DEF.");
const u8 gMoveDescription_Kinesis[] = _("The user distracts\nthe foe by bending\na spoon. It may\nlower accuracy.");
const u8 gMoveDescription_SoftBoiled[] = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_HiJumpKick[] = _("A strong jumping\nknee kick. If it\nmisses, the user is\nhurt.");
const u8 gMoveDescription_Glare[] = _("The user intimidates\nthe foe with the\ndesign on its belly\nto cause paralysis.");
const u8 gMoveDescription_DreamEater[] = _("Absorbs half the\ndamage it inflicted\non a sleeping foe\nto restore HP.");
const u8 gMoveDescription_PoisonGas[] = _("The foe is sprayed\nwith a cloud of\ntoxic gas that may\npoison the foe.");
const u8 gMoveDescription_Barrage[] = _("Round objects are\nhurled at the foe\nto strike two to\nfive times.");
const u8 gMoveDescription_LeechLife[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LovelyKiss[] = _("The user forces a\nkiss on the foe\nwith a scary face\nthat induces sleep.");
const u8 gMoveDescription_SkyAttack[] = _("A 2nd-turn attack\nmove with a high\ncritical-hit ratio.\nThe foe may flinch.");
const u8 gMoveDescription_Transform[] = _("The user transforms\ninto a copy of the\nfoe with even the\nsame move set.");
const u8 gMoveDescription_Bubble[] = _("A spray of bubbles\nhits the foe.\nIt may lower the\nfoe's SPEED stat.");
const u8 gMoveDescription_DizzyPunch[] = _("The foe is hit with\na rhythmic punch\nthat may leave it\nconfused.");
const u8 gMoveDescription_Spore[] = _("The user scatters\nbursts of fine\nspores that induce\nsleep.");
const u8 gMoveDescription_Flash[] = _("A blast of light\nthat cuts the foe's\naccuracy. It also\nilluminates caves.");
const u8 gMoveDescription_Psywave[] = _("The foe is attacked\nwith an odd, hot\nenergy wave that\nvaries in intensity.");
const u8 gMoveDescription_Splash[] = _("The user just flops\nand splashes around\nwithout having any\neffect.");
const u8 gMoveDescription_AcidArmor[] = _("The user alters its\ncells to liquefy\nitself and sharply\nraise DEFENSE.");
const u8 gMoveDescription_Crabhammer[] = _("A large pincer is\nused to hammer the\nfoe. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Explosion[] = _("The user explodes\nto inflict terrible\ndamage even while\nfainting itself.");
const u8 gMoveDescription_FurySwipes[] = _("The foe is raked\nwith sharp claws or\nscythes two to five\ntimes.");
const u8 gMoveDescription_Bonemerang[] = _("The user throws a\nbone that hits the\nfoe once, then once\nagain on return.");
const u8 gMoveDescription_Rest[] = _("The user sleeps for\ntwo turns to fully\nrestore HP and heal\nany status problem.");
const u8 gMoveDescription_RockSlide[] = _("Large boulders are\nhurled at the foe.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_HyperFang[] = _("The foe is attacked\nwith sharp fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_Sharpen[] = _("The user reduces\nits polygon count\nto sharpen edges\nand raise ATTACK.");
const u8 gMoveDescription_Conversion[] = _("The user changes\nits type to match\nthe type of one of\nits moves.");
const u8 gMoveDescription_TriAttack[] = _("A simultaneous\n3-beam attack that\nmay paralyze, burn,\nor freeze the foe.");
const u8 gMoveDescription_SuperFang[] = _("The user attacks\nwith sharp fangs\nand halves the\nfoe's HP.");
const u8 gMoveDescription_Slash[] = _("The foe is slashed\nwith claws, etc.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Substitute[] = _("The user creates a\ndecoy using one-\nquarter of its full\nHP.");
const u8 gMoveDescription_Struggle[] = _("An attack that is\nused only if there\nis no PP. It also\nhurts the user.");
const u8 gMoveDescription_Sketch[] = _("This move copies\nthe move last used\nby the foe, then\ndisappears.");
const u8 gMoveDescription_TripleKick[] = _("A 3-kick attack\nthat becomes more\npowerful with each\nsuccessive hit.");
const u8 gMoveDescription_Thief[] = _("An attack that may\ntake the foe's held\nitem if the user\nisn't holding one.");
const u8 gMoveDescription_SpiderWeb[] = _("Ensnares the foe \nwith sticky string\nso it doesn't flee\nor switch out.");
const u8 gMoveDescription_MindReader[] = _("The user predicts\nthe foe's action to\nensure its next\nattack hits.");
const u8 gMoveDescription_Nightmare[] = _("A sleeping foe is\nshown a nightmare\nthat inflicts some\ndamage every turn.");
const u8 gMoveDescription_FlameWheel[] = _("The user makes a\nfiery charge at the\nfoe. It may cause\na burn.");
const u8 gMoveDescription_Snore[] = _("An attack that can\nbe used only while\nasleep. It may\ncause flinching.");
const u8 gMoveDescription_Curse[] = _("A move that works\ndifferently for the\nGHOST-type and all\nthe other types.");
const u8 gMoveDescription_Flail[] = _("A desperate attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Conversion2[] = _("The user changes\ntype to make itself\nresistant to the\nlast attack it took.");
const u8 gMoveDescription_Aeroblast[] = _("A vortex of air is\nshot at the foe.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_CottonSpore[] = _("Cotton-like spores\ncling to the foe,\nsharply reducing\nits SPEED stat.");
const u8 gMoveDescription_Reversal[] = _("An all-out attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Spite[] = _("A move that cuts\n2 to 5 PP from the\nmove last used by\nthe foe.");
const u8 gMoveDescription_PowderSnow[] = _("Blasts the foe with\na snowy gust.\nIt may cause\nfreezing.");
const u8 gMoveDescription_Protect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_MachPunch[] = _("A punch thrown at\nblinding speed.\nIt is certain to\nstrike first.");
const u8 gMoveDescription_ScaryFace[] = _("Frightens the foe\nwith a scary face\nto sharply reduce\nits SPEED.");
const u8 gMoveDescription_FaintAttack[] = _("The user draws up\nclose to the foe\ndisarmingly, then\nhits without fail.");
const u8 gMoveDescription_SweetKiss[] = _("The user kisses\nthe foe with sweet\ncuteness that\ncauses confusion.");
const u8 gMoveDescription_BellyDrum[] = _("The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.");
const u8 gMoveDescription_SludgeBomb[] = _("Filthy sludge is\nhurled at the foe.\nIt may poison the\ntarget.");
const u8 gMoveDescription_MudSlap[] = _("Mud is hurled in\nthe foe's face to\ninflict damage and\nlower its accuracy.");
const u8 gMoveDescription_Octazooka[] = _("Ink is blasted in\nthe foe's face or\neyes to damage and\nlower accuracy.");
const u8 gMoveDescription_Spikes[] = _("A trap of spikes is\nlaid around the\nfoe's party to hurt\nfoes switching in.");
const u8 gMoveDescription_ZapCannon[] = _("An electric blast is\nfired like a cannon\nto inflict damage\nand paralyze.");
const u8 gMoveDescription_Foresight[] = _("Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_DestinyBond[] = _("If the user faints,\nthe foe delivering\nthe final hit also\nfaints.");
const u8 gMoveDescription_PerishSong[] = _("Any battler that\nhears this faints\nin three turns\nunless it switches.");
const u8 gMoveDescription_IcyWind[] = _("A chilling wind is\nused to attack.\nIt also lowers the\nSPEED stat.");
const u8 gMoveDescription_Detect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_BoneRush[] = _("The user strikes\nthe foe with a bone\nin hand two to five\ntimes.");
const u8 gMoveDescription_LockOn[] = _("The user locks on\nto the foe, making\nthe next move sure\nto hit.");
const u8 gMoveDescription_Outrage[] = _("The user thrashes\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_Sandstorm[] = _("A 5-turn sandstorm\nthat damages all\ntypes except ROCK,\nGROUND, and STEEL.");
const u8 gMoveDescription_GigaDrain[] = _("A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_Endure[] = _("The user endures\nany hit with 1 HP\nleft. It may fail if\nused in succession.");
const u8 gMoveDescription_Charm[] = _("The foe is charmed\nby the user's cute\nappeals, sharply\ncutting its ATTACK.");
const u8 gMoveDescription_Rollout[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit hits.");
const u8 gMoveDescription_FalseSwipe[] = _("A restrained attack\nthat always leaves\nthe foe with at\nleast 1 HP.");
const u8 gMoveDescription_Swagger[] = _("A move that makes\nthe foe confused,\nbut also sharply\nraises its ATTACK.");
const u8 gMoveDescription_MilkDrink[] = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_Spark[] = _("An electrically\ncharged tackle that\nmay also paralyze\nthe foe.");
const u8 gMoveDescription_FuryCutter[] = _("An attack that\ngrows stronger on\neach successive\nhit.");
const u8 gMoveDescription_SteelWing[] = _("The foe is hit with\nwings of steel.\nIt may also raise\nthe user's DEFENSE.");
const u8 gMoveDescription_MeanLook[] = _("The foe is fixed\nwith a mean look\nthat prevents it\nfrom escaping.");
const u8 gMoveDescription_Attract[] = _("If it is the other\ngender, the foe is\nmade infatuated and\nunlikely to attack.");
const u8 gMoveDescription_SleepTalk[] = _("While asleep, the\nuser randomly uses\none of the moves it\nknows.");
const u8 gMoveDescription_HealBell[] = _("A soothing bell\nchimes to heal the\nstatus problems of\nall allies.");
const u8 gMoveDescription_Return[] = _("This attack move\ngrows more powerful\nthe more the user\nlikes its TRAINER.");
const u8 gMoveDescription_Present[] = _("The foe is given a\nbooby-trapped gift.\nIt restores HP\nsometimes, however.");
const u8 gMoveDescription_Frustration[] = _("This attack move\ngrows more powerful\nthe less the user\nlikes its TRAINER.");
const u8 gMoveDescription_Safeguard[] = _("It protects the\nuser's party from\nall status problems\nfor five turns.");
const u8 gMoveDescription_PainSplit[] = _("The user adds its\nHP to the foe's HP,\nthen equally shares\nthe total HP.");
const u8 gMoveDescription_SacredFire[] = _("A mystical and\npowerful fire\nattack that may\ninflict a burn.");
const u8 gMoveDescription_Magnitude[] = _("A ground-shaking\nattack against all\nstanding POKéMON.\nIts power varies.");
const u8 gMoveDescription_DynamicPunch[] = _("The foe is punched\nwith the user's full\npower. It confuses\nthe foe if it hits.");
const u8 gMoveDescription_Megahorn[] = _("A brutal ramming\nattack delivered\nwith a tough and\nimpressive horn.");
const u8 gMoveDescription_DragonBreath[] = _("The foe is hit with\nan incredible blast\nof breath that may\nalso paralyze.");
const u8 gMoveDescription_BatonPass[] = _("The user switches\nout, passing along\nany stat changes\nto the new battler.");
const u8 gMoveDescription_Encore[] = _("Makes the foe use\nthe move it last\nused repeatedly for\ntwo to six turns.");
const u8 gMoveDescription_Pursuit[] = _("An attack move that\nworks especially\nwell on a foe that\nis switching out.");
const u8 gMoveDescription_RapidSpin[] = _("An attack that\nfrees the user from\nBIND, WRAP, LEECH\nSEED, and SPIKES.");
const u8 gMoveDescription_SweetScent[] = _("Allures the foe to\nreduce evasiveness.\nIt also attracts\nwild POKéMON.");
const u8 gMoveDescription_IronTail[] = _("An attack with a\nsteel-hard tail.\nIt may lower the\nfoe's DEFENSE stat.");
const u8 gMoveDescription_MetalClaw[] = _("The foe is attacked\nwith steel claws.\nIt may also raise\nthe user's ATTACK.");
const u8 gMoveDescription_VitalThrow[] = _("Makes the user\nattack after the\nfoe. In return,\nit will not miss.");
const u8 gMoveDescription_MorningSun[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Synthesis[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Moonlight[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_HiddenPower[] = _("An attack that\nvaries in type and\nintensity depending\non the user.");
const u8 gMoveDescription_CrossChop[] = _("The foe is hit with\ndouble chops.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Twister[] = _("A vicious twister\nattacks the foe.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_RainDance[] = _("A heavy rain falls\nfor five turns,\npowering up WATER-\ntype moves.");
const u8 gMoveDescription_SunnyDay[] = _("The sun blazes for\nfive turns, powering\nup FIRE-type\nmoves.");
const u8 gMoveDescription_Crunch[] = _("The foe is crunched\nwith sharp fangs.\nIt may lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_MirrorCoat[] = _("A retaliation move\nthat pays back the\nfoe's special attack\ndouble.");
const u8 gMoveDescription_PsychUp[] = _("The user hypnotizes\nitself into copying\nany stat change\nmade by the foe.");
const u8 gMoveDescription_ExtremeSpeed[] = _("A blindingly speedy\ncharge attack that\nalways goes before\nany other.");
const u8 gMoveDescription_AncientPower[] = _("An ancient power is\nused to attack. It\nmay also raise all\nthe user's stats.");
const u8 gMoveDescription_ShadowBall[] = _("A shadowy blob is\nhurled at the foe.\nMay also lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_FutureSight[] = _("Two turns after\nthis move is used,\nthe foe is attacked\npsychically.");
const u8 gMoveDescription_RockSmash[] = _("An attack that may\nalso cut DEFENSE.\nIt can also smash\ncracked boulders.");
const u8 gMoveDescription_Whirlpool[] = _("The foe is trapped\nin a fast, vicious\nwhirlpool for two\nto five turns.");
const u8 gMoveDescription_BeatUp[] = _("All party POKéMON\njoin in the attack.\nThe more allies,\nthe more damage.");
const u8 gMoveDescription_FakeOut[] = _("An attack that hits\nfirst and causes\nflinching. Usable\nonly on 1st turn.");
const u8 gMoveDescription_Uproar[] = _("The user attacks in\nan uproar that\nprevents sleep for\ntwo to five turns.");
const u8 gMoveDescription_Stockpile[] = _("The user charges\nup power for use\nlater. It can be\nused three times.");
const u8 gMoveDescription_SpitUp[] = _("The power built\nusing STOCKPILE is\nreleased at once\nfor attack.");
const u8 gMoveDescription_Swallow[] = _("The energy it built\nusing STOCKPILE is\nabsorbed to restore\nHP.");
const u8 gMoveDescription_HeatWave[] = _("The user exhales a\nheated breath to\nattack. It may also\ninflict a burn.");
const u8 gMoveDescription_Hail[] = _("A hailstorm lasting\nfive turns damages\nall POKéMON except\nthe ICE-type.");
const u8 gMoveDescription_Torment[] = _("It enrages the foe,\nmaking it incapable\nof using the same\nmove successively.");
const u8 gMoveDescription_Flatter[] = _("Flattery is used to\nconfuse the foe,\nbut its SP. ATK\nalso rises.");
const u8 gMoveDescription_WillOWisp[] = _("A sinister, bluish\nwhite flame is shot\nat the foe to\ninflict a burn.");
const u8 gMoveDescription_Memento[] = _("The user faints,\nbut sharply lowers\nthe foe's ATTACK\nand SP. ATK.");
const u8 gMoveDescription_Facade[] = _("An attack that is\nboosted if user is\nburned, poisoned,\nor paralyzed.");
const u8 gMoveDescription_FocusPunch[] = _("An attack that is\nexecuted last.\nThe user flinches\nif hit beforehand.");
const u8 gMoveDescription_SmellingSalt[] = _("Doubly effective on\na paralyzed foe,\nbut it also cures\nthe foe's paralysis.");
const u8 gMoveDescription_FollowMe[] = _("The user draws\nattention to itself,\nmaking foes attack\nonly the user.");
const u8 gMoveDescription_NaturePower[] = _("An attack that\nchanges type\ndepending on the\nuser's location.");
const u8 gMoveDescription_Charge[] = _("The user charges\npower to boost the\nELECTRIC move it\nuses next.");
const u8 gMoveDescription_Taunt[] = _("The foe is taunted\ninto a rage that\nallows it to use\nonly attack moves.");
const u8 gMoveDescription_HelpingHand[] = _("A move that boosts\nthe power of the\nally's attack in a\nbattle.");
const u8 gMoveDescription_Trick[] = _("A move that tricks\nthe foe into\ntrading held items\nwith the user.");
const u8 gMoveDescription_RolePlay[] = _("The user mimics the\nfoe completely and\ncopies the foe's\nability.");
const u8 gMoveDescription_Wish[] = _("A self-healing move\nthat restores half\nthe full HP on the\nnext turn.");
const u8 gMoveDescription_Assist[] = _("The user randomly\npicks and uses a\nmove of an allied\nPOKéMON.");
const u8 gMoveDescription_Ingrain[] = _("The user lays roots\nthat restore HP on\nevery turn.\nIt can't switch out.");
const u8 gMoveDescription_Superpower[] = _("A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.");
const u8 gMoveDescription_MagicCoat[] = _("Reflects back the\nfoe's LEECH SEED\nand any status-\ndamaging move.");
const u8 gMoveDescription_Recycle[] = _("A move that\nrecycles a used\nitem for use once\nmore.");
const u8 gMoveDescription_Revenge[] = _("An attack move that\ngains in intensity if\nthe target has hurt\nthe user.");
const u8 gMoveDescription_BrickBreak[] = _("An attack that also\nbreaks any barrier\nlike LIGHT SCREEN\nand REFLECT.");
const u8 gMoveDescription_Yawn[] = _("A huge yawn lulls\nthe foe into falling\nasleep on the next\nturn.");
const u8 gMoveDescription_KnockOff[] = _("Knocks down the\nfoe's held item to\nprevent its use\nduring the battle.");
const u8 gMoveDescription_Endeavor[] = _("Gains power the\nfewer HP the user\nhas compared with\nthe foe.");
const u8 gMoveDescription_Eruption[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SkillSwap[] = _("The user employs\nits psychic power\nto swap abilities\nwith the foe.");
const u8 gMoveDescription_Imprison[] = _("Prevents foes from\nusing any move\nthat is also known\nby the user.");
const u8 gMoveDescription_Refresh[] = _("A self-healing move\nthat cures the user\nof a poisoning,\nburn, or paralysis.");
const u8 gMoveDescription_Grudge[] = _("If the user faints,\nthis move deletes\nthe PP of the move\nthat finished it.");
const u8 gMoveDescription_Snatch[] = _("Steals the effects\nof the foe's\nhealing or status-\nchanging move.");
const u8 gMoveDescription_SecretPower[] = _("An attack that may\nhave an additional\neffect that varies\nwith the terrain.");
const u8 gMoveDescription_Dive[] = _("The user dives\nunderwater on the\nfirst turn and\nstrikes next turn.");
const u8 gMoveDescription_ArmThrust[] = _("A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.");
const u8 gMoveDescription_Camouflage[] = _("Alters the user's\ntype depending on\nthe location's\nterrain.");
const u8 gMoveDescription_TailGlow[] = _("The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.");
const u8 gMoveDescription_LusterPurge[] = _("A burst of light\ninjures the foe. It\nmay also lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_MistBall[] = _("A flurry of down\nhits the foe. It\nmay also lower the\nfoe's SP. ATK.");
const u8 gMoveDescription_FeatherDance[] = _("The foe is covered\nwith a mass of down\nthat sharply cuts\nthe ATTACK stat.");
const u8 gMoveDescription_TeeterDance[] = _("A wobbly dance\nthat confuses all\nthe POKéMON in\nbattle.");
const u8 gMoveDescription_BlazeKick[] = _("A fiery kick with a\nhigh critical-hit\nratio. It may also\nburn the foe.");
const u8 gMoveDescription_MudSport[] = _("Weakens ELECTRIC-\ntype attacks while\nthe user is in the\nbattle.");
const u8 gMoveDescription_IceBall[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit rolls.");
const u8 gMoveDescription_NeedleArm[] = _("An attack using\nthorny arms.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_SlackOff[] = _("The user slacks off\nand restores its HP\nby half its full\nHP.");
const u8 gMoveDescription_HyperVoice[] = _("The user lets loose\na horribly loud\nshout with the\npower to damage.");
const u8 gMoveDescription_PoisonFang[] = _("The foe is bitten\nwith toxic fangs.\nIt may also badly\npoison the foe.");
const u8 gMoveDescription_CrushClaw[] = _("The foe is attacked\nwith sharp claws.\nIt may also lower\nthe foe's DEFENSE.");
const u8 gMoveDescription_BlastBurn[] = _("The foe is hit with\na huge explosion.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_HydroCannon[] = _("The foe is hit with\na watery cannon.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_MeteorMash[] = _("The foe is hit with\na hard, fast punch.\nIt may also raise\nthe user's ATTACK.");
const u8 gMoveDescription_Astonish[] = _("An attack using a\nstartling shout.\nIt also may make\nthe foe flinch.");
const u8 gMoveDescription_WeatherBall[] = _("An attack that\nvaries in power and\ntype depending on\nthe weather.");
const u8 gMoveDescription_Aromatherapy[] = _("A soothing scent is\nreleased to heal\nall status problems\nin the user's party.");
const u8 gMoveDescription_FakeTears[] = _("The user feigns\ncrying to sharply\nlower the foe's\nSP. DEF stat.");
const u8 gMoveDescription_AirCutter[] = _("The foe is hit with\nrazor-like wind.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Overheat[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_OdorSleuth[] = _("Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_RockTomb[] = _("Boulders are hurled\nat the foe. It also\nlowers the foe's\nSPEED if it hits.");
const u8 gMoveDescription_SilverWind[] = _("The foe is attacked\nwith a silver dust.\nIt may raise all\nthe user's stats.");
const u8 gMoveDescription_MetalSound[] = _("A horrible metallic\nscreech is used to\nsharply lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_GrassWhistle[] = _("A pleasant melody\nis played to lull\nthe foe into a deep\nsleep.");
const u8 gMoveDescription_Tickle[] = _("The foe is made to\nlaugh, reducing its\nATTACK and DEFENSE\nstats.");
const u8 gMoveDescription_CosmicPower[] = _("The user absorbs a\nmystic power to\nraise its DEFENSE\nand SP. DEF.");
const u8 gMoveDescription_WaterSpout[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SignalBeam[] = _("The foe is hit with\na flashing beam\nthat may also\ncause confusion.");
const u8 gMoveDescription_ShadowPunch[] = _("The user throws a\npunch from the\nshadows. It cannot\nbe evaded.");
const u8 gMoveDescription_Extrasensory[] = _("The user attacks\nwith an odd power\nthat may make the\nfoe flinch.");
const u8 gMoveDescription_SkyUppercut[] = _("The user attacks\nwith an uppercut\nthrown skywards\nwith force.");
const u8 gMoveDescription_SandTomb[] = _("The foe is trapped\ninside a painful\nsandstorm for two\nto five turns.");
const u8 gMoveDescription_SheerCold[] = _("The foe is attacked\nwith ultimate cold\nthat causes fainting\nif it hits.");
const u8 gMoveDescription_MuddyWater[] = _("The user attacks\nwith muddy water.\nIt may also lower\nthe foe's accuracy.");
const u8 gMoveDescription_BulletSeed[] = _("The user shoots\nseeds at the foe.\nTwo to five seeds\nare shot at once.");
const u8 gMoveDescription_AerialAce[] = _("An extremely fast\nattack against one\ntarget. It can't be\nevaded.");
const u8 gMoveDescription_IcicleSpear[] = _("Sharp icicles are\nfired at the foe.\nIt strikes two to\nfive times.");
const u8 gMoveDescription_IronDefense[] = _("The user hardens\nits body's surface\nto sharply raise its\nDEFENSE stat.");
const u8 gMoveDescription_Block[] = _("The user blocks the\nfoe's way with arms\nspread wide to\nprevent escape.");
const u8 gMoveDescription_Howl[] = _("The user howls to\nraise its spirit and\nboost its ATTACK\nstat.");
const u8 gMoveDescription_DragonClaw[] = _("Sharp, huge claws\nhook and slash the\nfoe quickly and\nwith great power.");
const u8 gMoveDescription_FrenzyPlant[] = _("The foe is hit with\nan enormous branch.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_BulkUp[] = _("The user bulks up\nits body to boost\nboth its ATTACK and\nDEFENSE stats.");
const u8 gMoveDescription_Bounce[] = _("The user bounces\non the foe on the\n2nd turn. It may\nparalyze the foe.");
const u8 gMoveDescription_MudShot[] = _("The user attacks by\nhurling mud.\nIt also reduces the\nfoe's SPEED.");
const u8 gMoveDescription_PoisonTail[] = _("An attack with a\nhigh critical-hit\nratio. It may also\npoison the foe.");
const u8 gMoveDescription_Covet[] = _("A cutely executed\nattack that also\nsteals the foe's\nhold item.");
const u8 gMoveDescription_VoltTackle[] = _("The user throws an\nelectrified tackle.\nIt hurts the user\na little.");
const u8 gMoveDescription_MagicalLeaf[] = _("The foe is attacked\nwith a strange leaf\nthat cannot be\nevaded.");
const u8 gMoveDescription_WaterSport[] = _("Weakens FIRE-type\nattacks while the\nuser is in the\nbattle.");
const u8 gMoveDescription_CalmMind[] = _("The user focuses\nits mind to raise\nthe SP. ATK and\nSP. DEF stats.");
const u8 gMoveDescription_LeafBlade[] = _("The foe is slashed\nwith a sharp leaf.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_DragonDance[] = _("A mystic, powerful\ndance that boosts\nthe user's ATTACK\nand SPEED stats.");
const u8 gMoveDescription_RockBlast[] = _("The user hurls two\nto five hard rocks\nat the foe to\nattack.");
const u8 gMoveDescription_ShockWave[] = _("A rapid jolt of\nelectricity strikes\nthe foe. It can't\nbe evaded.");
const u8 gMoveDescription_WaterPulse[] = _("An attack with a\npulsing blast of\nwater. It may also\nconfuse the foe.");
const u8 gMoveDescription_DoomDesire[] = _("A move that attacks\nthe foe with a\nblast of light two\nturns after use.");
const u8 gMoveDescription_PsychoBoost[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_Dummy[] = _("lol\nlol\nlol\nlol");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND - 1] = gMoveDescription_Dummy,
    [MOVE_KARATE_CHOP - 1] = gMoveDescription_Dummy,
    [MOVE_FEINT - 1] = gMoveDescription_Dummy,
    [MOVE_COMET_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_MEGA_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_PAY_DAY - 1] = gMoveDescription_Dummy,
    [MOVE_FIRE_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_ICE_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_SCRATCH - 1] = gMoveDescription_Dummy,
    [MOVE_NIGHT_SLASH - 1] = gMoveDescription_Dummy,
    [MOVE_JUDGMENT - 1] = gMoveDescription_Dummy,
    [MOVE_RAZOR_WIND - 1] = gMoveDescription_Dummy,
    [MOVE_SWORDS_DANCE - 1] = gMoveDescription_Dummy,
    [MOVE_CUT - 1] = gMoveDescription_Dummy,
    [MOVE_GUST - 1] = gMoveDescription_Dummy,
    [MOVE_WING_ATTACK - 1] = gMoveDescription_Dummy,
    [MOVE_WHIRLWIND - 1] = gMoveDescription_Dummy,
    [MOVE_FLY - 1] = gMoveDescription_Dummy,
    [MOVE_BIND - 1] = gMoveDescription_Dummy,
    [MOVE_BRAVER - 1] = gMoveDescription_Dummy,
    [MOVE_VINE_WHIP - 1] = gMoveDescription_Dummy,
    [MOVE_STOMP - 1] = gMoveDescription_Dummy,
    [MOVE_DOUBLE_KICK - 1] = gMoveDescription_Dummy,
    [MOVE_MEGA_KICK - 1] = gMoveDescription_Dummy,
    [MOVE_JUMP_KICK - 1] = gMoveDescription_Dummy,
    [MOVE_ROLLING_KICK - 1] = gMoveDescription_Dummy,
    [MOVE_SAND_ATTACK - 1] = gMoveDescription_Dummy,
    [MOVE_HEADBUTT - 1] = gMoveDescription_Dummy,
    [MOVE_KNIFE_THROW - 1] = gMoveDescription_Dummy,
    [MOVE_MAGIC_KNIFE - 1] = gMoveDescription_Dummy,
    [MOVE_SCULPTURE - 1] = gMoveDescription_Dummy,
    [MOVE_TACKLE - 1] = gMoveDescription_Dummy,
    [MOVE_BODY_SLAM - 1] = gMoveDescription_Dummy,
    [MOVE_WRAP - 1] = gMoveDescription_Dummy,
    [MOVE_TAKE_DOWN - 1] = gMoveDescription_Dummy,
    [MOVE_THRASH - 1] = gMoveDescription_Dummy,
    [MOVE_DOUBLE_EDGE - 1] = gMoveDescription_Dummy,
    [MOVE_TAIL_WHIP - 1] = gMoveDescription_Dummy,
    [MOVE_POISON_STING - 1] = gMoveDescription_Dummy,
    [MOVE_SEAL_NEEDLE - 1] = gMoveDescription_Dummy,
    [MOVE_PIN_MISSILE - 1] = gMoveDescription_Dummy,
    [MOVE_LEER - 1] = gMoveDescription_Dummy,
    [MOVE_BITE - 1] = gMoveDescription_Dummy,
    [MOVE_GROWL - 1] = gMoveDescription_Dummy,
    [MOVE_ROAR - 1] = gMoveDescription_Dummy,
    [MOVE_SING - 1] = gMoveDescription_Dummy,
    [MOVE_JAMMING - 1] = gMoveDescription_Dummy,
    [MOVE_SONICBOOM - 1] = gMoveDescription_Dummy,
    [MOVE_DISABLE - 1] = gMoveDescription_Dummy,
    [MOVE_POISON_TEARS - 1] = gMoveDescription_Dummy,
    [MOVE_EMBER - 1] = gMoveDescription_Dummy,
    [MOVE_FLAMETHROWER - 1] = gMoveDescription_Dummy,
    [MOVE_MIST - 1] = gMoveDescription_Dummy,
    [MOVE_WATER_GUN - 1] = gMoveDescription_Dummy,
    [MOVE_HYDRO_PUMP - 1] = gMoveDescription_Dummy,
    [MOVE_SURF - 1] = gMoveDescription_Dummy,
    [MOVE_ICE_BEAM - 1] = gMoveDescription_Dummy,
    [MOVE_BLIZZARD - 1] = gMoveDescription_Dummy,
    [MOVE_PSYBEAM - 1] = gMoveDescription_Dummy,
    [MOVE_BUBBLEBEAM - 1] = gMoveDescription_Dummy,
    [MOVE_AURORA_BEAM - 1] = gMoveDescription_Dummy,
    [MOVE_HYPER_BEAM - 1] = gMoveDescription_Dummy,
    [MOVE_PECK - 1] = gMoveDescription_Dummy,
    [MOVE_FOUL_PLAY - 1] = gMoveDescription_Dummy,
    [MOVE_SUBMISSION - 1] = gMoveDescription_Dummy,
    [MOVE_SKANDAS_LEG - 1] = gMoveDescription_Dummy,
    [MOVE_COUNTER - 1] = gMoveDescription_Dummy,
    [MOVE_SEISMIC_TOSS - 1] = gMoveDescription_Dummy,
    [MOVE_STRENGTH - 1] = gMoveDescription_Dummy,
    [MOVE_ABSORB - 1] = gMoveDescription_Dummy,
    [MOVE_MEGA_DRAIN - 1] = gMoveDescription_Dummy,
    [MOVE_LEECH_SEED - 1] = gMoveDescription_Dummy,
    [MOVE_GROWTH - 1] = gMoveDescription_Dummy,
    [MOVE_RAZOR_LEAF - 1] = gMoveDescription_Dummy,
    [MOVE_SOLAR_BEAM - 1] = gMoveDescription_Dummy,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_Dummy,
    [MOVE_STUN_SPORE - 1] = gMoveDescription_Dummy,
    [MOVE_SLEEP_POWDER - 1] = gMoveDescription_Dummy,
    [MOVE_PETAL_STORM - 1] = gMoveDescription_Dummy,
    [MOVE_MESMERISM - 1] = gMoveDescription_Dummy,
    [MOVE_DARK_PULSE - 1] = gMoveDescription_Dummy,
    [MOVE_FIRE_SPIN - 1] = gMoveDescription_Dummy,
    [MOVE_THUNDERSHOCK - 1] = gMoveDescription_Dummy,
    [MOVE_THUNDERBOLT - 1] = gMoveDescription_Dummy,
    [MOVE_THUNDER_WAVE - 1] = gMoveDescription_Dummy,
    [MOVE_THUNDER - 1] = gMoveDescription_Dummy,
    [MOVE_ROCK_WRECKER - 1] = gMoveDescription_Dummy,
    [MOVE_EARTHQUAKE - 1] = gMoveDescription_Dummy,
    [MOVE_FISSURE - 1] = gMoveDescription_Dummy,
    [MOVE_DIG - 1] = gMoveDescription_Dummy,
    [MOVE_TOXIC - 1] = gMoveDescription_Dummy,
    [MOVE_PSYSHOT - 1] = gMoveDescription_Dummy,
    [MOVE_MANA_BURST - 1] = gMoveDescription_Dummy,
    [MOVE_HYPNOSIS - 1] = gMoveDescription_Dummy,
    [MOVE_ZEN_HEADBUTT - 1] = gMoveDescription_Dummy,
    [MOVE_AGILITY - 1] = gMoveDescription_Dummy,
    [MOVE_QUICK_ATTACK - 1] = gMoveDescription_Dummy,
    [MOVE_RAGE - 1] = gMoveDescription_Dummy,
    [MOVE_TELEPORT - 1] = gMoveDescription_Dummy,
    [MOVE_NIGHT_SHADE - 1] = gMoveDescription_Dummy,
    [MOVE_MIMIC - 1] = gMoveDescription_Dummy,
    [MOVE_SCREECH - 1] = gMoveDescription_Dummy,
    [MOVE_DOUBLE_TEAM - 1] = gMoveDescription_Dummy,
    [MOVE_RECOVER - 1] = gMoveDescription_Dummy,
    [MOVE_HARDEN - 1] = gMoveDescription_Dummy,
    [MOVE_MINIMIZE - 1] = gMoveDescription_Dummy,
    [MOVE_SMOKESCREEN - 1] = gMoveDescription_Dummy,
    [MOVE_CONFUSE_RAY - 1] = gMoveDescription_Dummy,
    [MOVE_WITHDRAW - 1] = gMoveDescription_Dummy,
    [MOVE_DEFENSE_CURL - 1] = gMoveDescription_Dummy,
    [MOVE_BARRIER - 1] = gMoveDescription_Dummy,
    [MOVE_LIGHT_SCREEN - 1] = gMoveDescription_Dummy,
    [MOVE_HAZE - 1] = gMoveDescription_Dummy,
    [MOVE_REFLECT - 1] = gMoveDescription_Dummy,
    [MOVE_FOCUS_ENERGY - 1] = gMoveDescription_Dummy,
    [MOVE_WORK_UP - 1] = gMoveDescription_Dummy,
    [MOVE_METRONOME - 1] = gMoveDescription_Dummy,
    [MOVE_DEBT_SPIRAL - 1] = gMoveDescription_Dummy,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_Dummy,
    [MOVE_MIND_BOMB - 1] = gMoveDescription_Dummy,
    [MOVE_LICK - 1] = gMoveDescription_Dummy,
    [MOVE_SMOG - 1] = gMoveDescription_Dummy,
    [MOVE_GUNK_SHOT - 1] = gMoveDescription_Dummy,
    [MOVE_WOOD_HAMMER - 1] = gMoveDescription_Dummy,
    [MOVE_FIRE_BLAST - 1] = gMoveDescription_Dummy,
    [MOVE_WATERFALL - 1] = gMoveDescription_Dummy,
    [MOVE_MANA_SHIELD - 1] = gMoveDescription_Dummy,
    [MOVE_SWIFT - 1] = gMoveDescription_Dummy,
    [MOVE_SKULL_BASH - 1] = gMoveDescription_Dummy,
    [MOVE_DANMAKU - 1] = gMoveDescription_Dummy,
    [MOVE_TOPSY_TURVY - 1] = gMoveDescription_Dummy,
    [MOVE_AMNESIA - 1] = gMoveDescription_Dummy,
    [MOVE_LUNA_DIAL - 1] = gMoveDescription_Dummy,
    [MOVE_SOFT_BOILED - 1] = gMoveDescription_Dummy,
    [MOVE_HI_JUMP_KICK - 1] = gMoveDescription_Dummy,
    [MOVE_DAUNT - 1] = gMoveDescription_Dummy,
    [MOVE_DREAM_EATER - 1] = gMoveDescription_Dummy,
    [MOVE_OMINOUS_WIND - 1] = gMoveDescription_Dummy,
    [MOVE_BARRAGE - 1] = gMoveDescription_Dummy,
    [MOVE_LEECH_LIFE - 1] = gMoveDescription_Dummy,
    [MOVE_LOVELY_KISS - 1] = gMoveDescription_Dummy,
    [MOVE_SKY_ATTACK - 1] = gMoveDescription_Dummy,
    [MOVE_TRANSFORM - 1] = gMoveDescription_Dummy,
    [MOVE_BUBBLE - 1] = gMoveDescription_Dummy,
    [MOVE_DIZZY_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_BURN_POWDER - 1] = gMoveDescription_Dummy,
    [MOVE_FLASH - 1] = gMoveDescription_Dummy,
    [MOVE_PSYWAVE - 1] = gMoveDescription_Dummy,
    [MOVE_SPLASH - 1] = gMoveDescription_Dummy,
    [MOVE_DISPERSE - 1] = gMoveDescription_Dummy,
    [MOVE_AQUA_JET - 1] = gMoveDescription_Dummy,
    [MOVE_EXPLOSION - 1] = gMoveDescription_Dummy,
    [MOVE_FURY_SWIPES - 1] = gMoveDescription_Dummy,
    [MOVE_SUCKER_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_REST - 1] = gMoveDescription_Dummy,
    [MOVE_ROCK_SLIDE - 1] = gMoveDescription_Dummy,
    [MOVE_KILLING_BITE - 1] = gMoveDescription_Dummy,
    [MOVE_SHARPEN - 1] = gMoveDescription_Dummy,
    [MOVE_CONVERSION - 1] = gMoveDescription_Dummy,
    [MOVE_TRI_ATTACK - 1] = gMoveDescription_Dummy,
    [MOVE_GIGA_IMPACT - 1] = gMoveDescription_Dummy,
    [MOVE_SLASH - 1] = gMoveDescription_Dummy,
    [MOVE_SUBSTITUTE - 1] = gMoveDescription_Dummy,
    [MOVE_STRUGGLE - 1] = gMoveDescription_Dummy,
    [MOVE_SKETCH - 1] = gMoveDescription_Dummy,
    [MOVE_SHADOW_SNEAK - 1] = gMoveDescription_Dummy,
    [MOVE_THIEF - 1] = gMoveDescription_Dummy,
    [MOVE_SPIDER_WEB - 1] = gMoveDescription_Dummy,
    [MOVE_HEARTS_EYE - 1] = gMoveDescription_Dummy,
    [MOVE_NIGHTMARE - 1] = gMoveDescription_Dummy,
    [MOVE_FLAME_WHEEL - 1] = gMoveDescription_Dummy,
    [MOVE_SNORE - 1] = gMoveDescription_Dummy,
    [MOVE_CURSE - 1] = gMoveDescription_Dummy,
    [MOVE_FLAIL - 1] = gMoveDescription_Dummy,
    [MOVE_CONVERSION_2 - 1] = gMoveDescription_Dummy,
    [MOVE_AEROBLAST - 1] = gMoveDescription_Dummy,
    [MOVE_COTTON_SPORE - 1] = gMoveDescription_Dummy,
    [MOVE_REVERSAL - 1] = gMoveDescription_Dummy,
    [MOVE_SPITE - 1] = gMoveDescription_Dummy,
    [MOVE_POWDER_SNOW - 1] = gMoveDescription_Dummy,
    [MOVE_PROTECT - 1] = gMoveDescription_Dummy,
    [MOVE_MACH_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_SCARY_FACE - 1] = gMoveDescription_Dummy,
    [MOVE_FEINT_ATTACK - 1] = gMoveDescription_Dummy,
    [MOVE_SWEET_KISS - 1] = gMoveDescription_Dummy,
    [MOVE_BELLY_DRUM - 1] = gMoveDescription_Dummy,
    [MOVE_POISON_BOMB - 1] = gMoveDescription_Dummy,
    [MOVE_MUD_SLAP - 1] = gMoveDescription_Dummy,
    [MOVE_BLACK_RIPPLE - 1] = gMoveDescription_Dummy,
    [MOVE_SPIKES - 1] = gMoveDescription_Dummy,
    [MOVE_DISCHARGE - 1] = gMoveDescription_Dummy,
    [MOVE_FORESIGHT - 1] = gMoveDescription_Dummy,
    [MOVE_DESTINY_BOND - 1] = gMoveDescription_Dummy,
    [MOVE_PERISH_SONG - 1] = gMoveDescription_Dummy,
    [MOVE_ICY_WIND - 1] = gMoveDescription_Dummy,
    [MOVE_DETECT - 1] = gMoveDescription_Dummy,
    [MOVE_HEAD_RUSH - 1] = gMoveDescription_Dummy,
    [MOVE_LOCK_ON - 1] = gMoveDescription_Dummy,
    [MOVE_OUTRAGE - 1] = gMoveDescription_Dummy,
    [MOVE_SANDSTORM - 1] = gMoveDescription_Dummy,
    [MOVE_GIGA_DRAIN - 1] = gMoveDescription_Dummy,
    [MOVE_ENDURE - 1] = gMoveDescription_Dummy,
    [MOVE_SMILE - 1] = gMoveDescription_Dummy,
    [MOVE_TREMORS - 1] = gMoveDescription_Dummy,
    [MOVE_FALSE_SWIPE - 1] = gMoveDescription_Dummy,
    [MOVE_SWAGGER - 1] = gMoveDescription_Dummy,
    [MOVE_HOSPITALITY - 1] = gMoveDescription_Dummy,
    [MOVE_SPARK - 1] = gMoveDescription_Dummy,
    [MOVE_FURY_CUTTER - 1] = gMoveDescription_Dummy,
    [MOVE_STEEL_WING - 1] = gMoveDescription_Dummy,
    [MOVE_LURE_OF_DEATH - 1] = gMoveDescription_Dummy,
    [MOVE_ATTRACT - 1] = gMoveDescription_Dummy,
    [MOVE_SLEEP_TALK - 1] = gMoveDescription_Dummy,
    [MOVE_HEAL_BELL - 1] = gMoveDescription_Dummy,
    [MOVE_FINAL_GAMBIT - 1] = gMoveDescription_Dummy,
    [MOVE_PRANK - 1] = gMoveDescription_Dummy,
    [MOVE_FRUSTRATION - 1] = gMoveDescription_Dummy,
    [MOVE_SAFEGUARD - 1] = gMoveDescription_Dummy,
    [MOVE_PAIN_SPLIT - 1] = gMoveDescription_Dummy,
    [MOVE_SACRED_FIRE - 1] = gMoveDescription_Dummy,
    [MOVE_MAGNITUDE - 1] = gMoveDescription_Dummy,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_BRAVE_BIRD - 1] = gMoveDescription_Dummy,
    [MOVE_LAVA_PLUME - 1] = gMoveDescription_Dummy,
    [MOVE_BATON_PASS - 1] = gMoveDescription_Dummy,
    [MOVE_ENCORE - 1] = gMoveDescription_Dummy,
    [MOVE_PURSUIT - 1] = gMoveDescription_Dummy,
    [MOVE_RAPID_SPIN - 1] = gMoveDescription_Dummy,
    [MOVE_NATURE_POWER - 1] = gMoveDescription_Dummy,
    [MOVE_STEEL_FIST - 1] = gMoveDescription_Dummy,
    [MOVE_METAL_CLAW - 1] = gMoveDescription_Dummy,
    [MOVE_VITAL_THROW - 1] = gMoveDescription_Dummy,
    [MOVE_ENERGY_LIGHT - 1] = gMoveDescription_Dummy,
    [MOVE_SYNTHESIS - 1] = gMoveDescription_Dummy,
    [MOVE_LUNATIC - 1] = gMoveDescription_Dummy,
    [MOVE_HIDDEN_POWER - 1] = gMoveDescription_Dummy,
    [MOVE_CROSS_CHOP - 1] = gMoveDescription_Dummy,
    [MOVE_SHOCK_SPIN - 1] = gMoveDescription_Dummy,
    [MOVE_RAIN_DANCE - 1] = gMoveDescription_Dummy,
    [MOVE_SUNNY_DAY - 1] = gMoveDescription_Dummy,
    [MOVE_CRUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_MIRROR_COAT - 1] = gMoveDescription_Dummy,
    [MOVE_PSYCH_UP - 1] = gMoveDescription_Dummy,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_Dummy,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_Dummy,
    [MOVE_SHADOW_BALL - 1] = gMoveDescription_Dummy,
    [MOVE_PSYCHO_CUT - 1] = gMoveDescription_Dummy,
    [MOVE_ROCK_SMASH - 1] = gMoveDescription_Dummy,
    [MOVE_WHIRLPOOL - 1] = gMoveDescription_Dummy,
    [MOVE_DRAWN_LINE - 1] = gMoveDescription_Dummy,
    [MOVE_FAKE_OUT - 1] = gMoveDescription_Dummy,
    [MOVE_PERFORMANCE - 1] = gMoveDescription_Dummy,
    [MOVE_NASTY_PLOT - 1] = gMoveDescription_Dummy,
    [MOVE_MIRROR_SHOT - 1] = gMoveDescription_Dummy,
    [MOVE_AQUA_RING - 1] = gMoveDescription_Dummy,
    [MOVE_HEAT_WAVE - 1] = gMoveDescription_Dummy,
    [MOVE_HAIL - 1] = gMoveDescription_Dummy,
    [MOVE_TORMENT - 1] = gMoveDescription_Dummy,
    [MOVE_LUCKY_CHANT - 1] = gMoveDescription_Dummy,
    [MOVE_WILL_O_WISP - 1] = gMoveDescription_Dummy,
    [MOVE_MEMENTO - 1] = gMoveDescription_Dummy,
    [MOVE_FACADE - 1] = gMoveDescription_Dummy,
    [MOVE_FOCUS_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_Dummy,
    [MOVE_COPYCAT - 1] = gMoveDescription_Dummy,
    [MOVE_ROCK_BULLET - 1] = gMoveDescription_Dummy,
    [MOVE_CHARGE - 1] = gMoveDescription_Dummy,
    [MOVE_TAUNT - 1] = gMoveDescription_Dummy,
    [MOVE_HELPING_HAND - 1] = gMoveDescription_Dummy,
    [MOVE_TRICK - 1] = gMoveDescription_Dummy,
    [MOVE_RECOLLECTION - 1] = gMoveDescription_Dummy,
    [MOVE_WISH - 1] = gMoveDescription_Dummy,
    [MOVE_ASSIST - 1] = gMoveDescription_Dummy,
    [MOVE_INGRAIN - 1] = gMoveDescription_Dummy,
    [MOVE_SUPERPOWER - 1] = gMoveDescription_Dummy,
    [MOVE_MAGIC_COAT - 1] = gMoveDescription_Dummy,
    [MOVE_RECYCLE - 1] = gMoveDescription_Dummy,
    [MOVE_REVENGE - 1] = gMoveDescription_Dummy,
    [MOVE_BRICK_BREAK - 1] = gMoveDescription_Dummy,
    [MOVE_YAWN - 1] = gMoveDescription_Dummy,
    [MOVE_KNOCK_OFF - 1] = gMoveDescription_Dummy,
    [MOVE_ENDEAVOR - 1] = gMoveDescription_Dummy,
    [MOVE_ERUPTION - 1] = gMoveDescription_Dummy,
    [MOVE_SKILL_SWAP - 1] = gMoveDescription_Dummy,
    [MOVE_IMPRISON - 1] = gMoveDescription_Dummy,
    [MOVE_REFRESH - 1] = gMoveDescription_Dummy,
    [MOVE_SHADOW_DANCE - 1] = gMoveDescription_Dummy,
    [MOVE_SNATCH - 1] = gMoveDescription_Dummy,
    [MOVE_SECRET_POWER - 1] = gMoveDescription_Dummy,
    [MOVE_SHADOW_FORCE - 1] = gMoveDescription_Dummy,
    [MOVE_FORCE_PALM - 1] = gMoveDescription_Dummy,
    [MOVE_CAMOUFLAGE - 1] = gMoveDescription_Dummy,
    [MOVE_MANA_CHARGE - 1] = gMoveDescription_Dummy,
    [MOVE_LUSTER_PURGE - 1] = gMoveDescription_Dummy,
    [MOVE_MIST_BALL - 1] = gMoveDescription_Dummy,
    [MOVE_ROOST - 1] = gMoveDescription_Dummy,
    [MOVE_TEETER_DANCE - 1] = gMoveDescription_Dummy,
    [MOVE_BLAZE_KICK - 1] = gMoveDescription_Dummy,
    [MOVE_EARTH_POWER - 1] = gMoveDescription_Dummy,
    [MOVE_ICE_BALL - 1] = gMoveDescription_Dummy,
    [MOVE_NEEDLE_ARM - 1] = gMoveDescription_Dummy,
    [MOVE_SLACK_OFF - 1] = gMoveDescription_Dummy,
    [MOVE_HYPER_VOICE - 1] = gMoveDescription_Dummy,
    [MOVE_CROSS_POISON - 1] = gMoveDescription_Dummy,
    [MOVE_CRUSH_CLAW - 1] = gMoveDescription_Dummy,
    [MOVE_FLARE_BLITZ - 1] = gMoveDescription_Dummy,
    [MOVE_DAM_BREACH - 1] = gMoveDescription_Dummy,
    [MOVE_METEOR_MASH - 1] = gMoveDescription_Dummy,
    [MOVE_ASTONISH - 1] = gMoveDescription_Dummy,
    [MOVE_WEATHER_BALL - 1] = gMoveDescription_Dummy,
    [MOVE_AROMATHERAPY - 1] = gMoveDescription_Dummy,
    [MOVE_FAKE_TEARS - 1] = gMoveDescription_Dummy,
    [MOVE_AIR_SLASH - 1] = gMoveDescription_Dummy,
    [MOVE_OVERHEAT - 1] = gMoveDescription_Dummy,
    [MOVE_SHADOW_HIT - 1] = gMoveDescription_Dummy,
    [MOVE_ROCK_TOMB - 1] = gMoveDescription_Dummy,
    [MOVE_SILVER_WIND - 1] = gMoveDescription_Dummy,
    [MOVE_BINDING_VOICE - 1] = gMoveDescription_Dummy,
    [MOVE_NATURE_SOUND - 1] = gMoveDescription_Dummy,
    [MOVE_TICKLE - 1] = gMoveDescription_Dummy,
    [MOVE_DRACO_METEOR - 1] = gMoveDescription_Dummy,
    [MOVE_AQUA_SHOWER - 1] = gMoveDescription_Dummy,
    [MOVE_SIGNAL_BEAM - 1] = gMoveDescription_Dummy,
    [MOVE_SHADOW_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_EXTRASENSORY - 1] = gMoveDescription_Dummy,
    [MOVE_SOAR - 1] = gMoveDescription_Dummy,
    [MOVE_SAND_TOMB - 1] = gMoveDescription_Dummy,
    [MOVE_COLD_SNAP - 1] = gMoveDescription_Dummy,
    [MOVE_MUDDY_WATER - 1] = gMoveDescription_Dummy,
    [MOVE_BULLET_SEED - 1] = gMoveDescription_Dummy,
    [MOVE_BLADE_FLASH - 1] = gMoveDescription_Dummy,
    [MOVE_ICE_SHARD - 1] = gMoveDescription_Dummy,
    [MOVE_IRON_DEFENSE - 1] = gMoveDescription_Dummy,
    [MOVE_BLOCK - 1] = gMoveDescription_Dummy,
    [MOVE_HOWL - 1] = gMoveDescription_Dummy,
    [MOVE_HEAT_CLAW - 1] = gMoveDescription_Dummy,
    [MOVE_LEAF_STORM - 1] = gMoveDescription_Dummy,
    [MOVE_BULK_UP - 1] = gMoveDescription_Dummy,
    [MOVE_BOUNCE - 1] = gMoveDescription_Dummy,
    [MOVE_MUD_SHOT - 1] = gMoveDescription_Dummy,
    [MOVE_POISON_JAB - 1] = gMoveDescription_Dummy,
    [MOVE_COVET - 1] = gMoveDescription_Dummy,
    [MOVE_VOLT_TACKLE - 1] = gMoveDescription_Dummy,
    [MOVE_MAGICAL_LEAF - 1] = gMoveDescription_Dummy,
    [MOVE_SPLASHBACK - 1] = gMoveDescription_Dummy,
    [MOVE_CALM_MIND - 1] = gMoveDescription_Dummy,
    [MOVE_LEAF_BLADE - 1] = gMoveDescription_Dummy,
    [MOVE_GALE_DANCE - 1] = gMoveDescription_Dummy,
    [MOVE_ROCK_BLAST - 1] = gMoveDescription_Dummy,
    [MOVE_SHOCK_WAVE - 1] = gMoveDescription_Dummy,
    [MOVE_WATER_PULSE - 1] = gMoveDescription_Dummy,
    [MOVE_APOLLON - 1] = gMoveDescription_Dummy,
    [MOVE_PSYCHO_BOOST - 1] = gMoveDescription_Dummy,
    [MOVE_DRAIN_PUNCH - 1] = gMoveDescription_Dummy,
    [MOVE_AURA_SPHERE - 1] = gMoveDescription_Dummy,
    [MOVE_FOCUS_BLAST - 1] = gMoveDescription_Dummy,
    [MOVE_HEART_BREAK - 1] = gMoveDescription_Dummy,
    [MOVE_DECISION - 1] = gMoveDescription_Dummy,
    [MOVE_RAPID_FIRE - 1] = gMoveDescription_Dummy,
    [MOVE_HEAD_SMASH - 1] = gMoveDescription_Dummy,
    [MOVE_SEED_BOMB - 1] = gMoveDescription_Dummy,
    [MOVE_FREEZE_DRY - 1] = gMoveDescription_Dummy,
    [MOVE_HONE_CLAWS - 1] = gMoveDescription_Dummy,
    [MOVE_QUIVER_DANCE - 1] = gMoveDescription_Dummy,
    [MOVE_SHELL_SMASH - 1] = gMoveDescription_Dummy,
    [MOVE_CLOSE_COMBAT - 1] = gMoveDescription_Dummy,
    [MOVE_DARK_VOID - 1] = gMoveDescription_Dummy,
    [MOVE_TRICK_ROOM - 1] = gMoveDescription_Dummy,
    [MOVE_TAILWIND - 1] = gMoveDescription_Dummy,
    [MOVE_U_TURN - 1] = gMoveDescription_Dummy,
    [MOVE_VOLT_SWITCH - 1] = gMoveDescription_Dummy,
    [MOVE_PURIFY - 1] = gMoveDescription_Dummy,
    [MOVE_HORSEPOWER - 1] = gMoveDescription_Dummy,
    [MOVE_HEALING_WISH - 1] = gMoveDescription_Dummy,
    [MOVE_GALE - 1] = gMoveDescription_Dummy,
    [MOVE_ABYSS_NOVA - 1] = gMoveDescription_Dummy,
    [MOVE_MISHAGUJI - 1] = gMoveDescription_Dummy,
    [MOVE_AEGIS_MERGE - 1] = gMoveDescription_Dummy,
    [MOVE_EXTERMINATE - 1] = gMoveDescription_Dummy,
    [MOVE_OBLIVION_WING - 1] = gMoveDescription_Dummy,
    [MOVE_FIRE_FANG - 1] = gMoveDescription_Dummy,
    [MOVE_ICE_FANG - 1] = gMoveDescription_Dummy,
    [MOVE_THUNDER_FANG - 1] = gMoveDescription_Dummy,
    [MOVE_ACUPRESSURE - 1] = gMoveDescription_Dummy,
    [MOVE_WILD_HUNT - 1] = gMoveDescription_Dummy,
    [MOVE_MANASHOCK - 1] = gMoveDescription_Dummy,
    [MOVE_FLAME_CHARGE - 1] = gMoveDescription_Dummy,
    [MOVE_CHARGE_BEAM - 1] = gMoveDescription_Dummy,
    [MOVE_PSYCHO_SHIFT - 1] = gMoveDescription_Dummy,
    [MOVE_BESTOW - 1] = gMoveDescription_Dummy,
    [MOVE_HEX - 1] = gMoveDescription_Dummy,
    [MOVE_POWER_WHIP - 1] = gMoveDescription_Dummy,
    [MOVE_ME_FIRST - 1] = gMoveDescription_Dummy,
};
