CeladonCity_Text_GotMyKoffingInCinnabar:: @ 817FEC3
    .string "I got my Flandre in Cinnabar.\p"
    .string "It's usually nice, but it breaks\n"
    .string "my toys when it's angry.$"

CeladonCity_Text_GymIsGreatFullOfWomen:: @ 817FF1C
    .string "Heheh! This Gym is great!\n"
    .string "It's full of women!$"

CeladonCity_Text_GameCornerIsBadForCitysImage:: @ 817FF4A
    .string "Celadon takes pride in its efforts\n"
    .string "to keep the city beautiful.\p"
    .string "That's why the new Game Corner is\n"
    .string "bad for our city's image.$"

CeladonCity_Text_BlewItAllAtSlots:: @ 817FFC5
    .string "Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I should have cashed in my\n"
    .string "Coins for prizes!$"

CeladonCity_Text_MyTrustedPalPoliwrath:: @ 818001B
    .string "This is my trusted pal, Poliwrath.\p"
    .string "It evolved from a Poliwhirl when\n"
    .string "I used a Water Stone.\p"
	.string "But, I hear Puppets have to hold\n"
	.string "special shards instead of using them.$"

CeladonCity_Text_Poliwrath:: @ 8180075
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou:: @ 818008C
    .string "What are you staring at?\n"
    .string "Get lost, or I'll punch you.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay:: @ 81800C2
    .string "Keep out of Team Rocket's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit:: @ 81800E1
    .string "TRAINER TIPS\p"
    .string "X Accuracy boosts the accuracy of\n"
    .string "techniques.\p"
    .string "Dire Hit jacks up the likelihood\n"
    .string "of critical hits.\p"
    .string "Get your items at the Celadon\n"
    .string "Dept. Store!$"

CeladonCity_Text_CitySign:: @ 818017A
    .string "CELADON CITY\n"
    .string "The City of Rainbow Dreams$"

CeladonCity_Text_GymSign:: @ 81801A2
    .string "CELADON CITY PUPPETRY GYM\n"
    .string "LEADER: Erika\l"
    .string "The Nature-Loving Princess!$"

CeladonCity_Text_MansionSign:: @ 81801E5
    .string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign:: @ 81801F5
    .string "Find what you need at the\n"
    .string "Celadon Dept. Store!$"

CeladonCity_Text_GuardSpecProtectsFromStatus:: @ 8180224
    .string "TRAINER TIPS\p"
    .string "Guard Spec. protects Puppets\n"
    .string "from status-reduction moves during\l"
    .string "battle.\p"
    .string "Get your items at the\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign:: @ 81802A4
    .string "Coins exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"

CeladonCity_Text_GameCornerSign:: @ 81802CF
    .string "ROCKET GAME CORNER\n"
    .string "The playground for grown-ups!$"

CeladonCity_Text_ScaldedTongueOnTea:: @ 8180300
    .string "Aaaagh, ow…\n"
    .string "I scalded my tongue!\p"
    .string "This nice guy named Koga\n"
    .string "gave me some Tea.\p"
    .string "But it was boiling hot!\n"
    .string "Gotta cool it to drink it.$"

Text_SoftboiledTeach:: @ 8180388
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move SOFTBOILED.$"

Text_SoftboiledDeclined:: @ 818043F
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

Text_SoftboiledWhichMon:: @ 8180484
    .string "So, who's the POKéMON that gets\n"
    .string "the chance to learn SOFTBOILED?$"

Text_SoftboiledTaught:: @ 81804C4
    .string "I wish you the best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope:: @ 81804E1
    .string "Oh, what am I to do…\p"
    .string "Someone stole our Silph Scope.\p"
    .string "The thief came running this way,\n"
    .string "I'm sure of it.\p"
    .string "But I lost sight of him!\n"
    .string "Where'd he go?$"

