BattleTower_BattleRoom_Text_RestorePuppets::
	.string "We will restore your Puppets\n"
	.string "to full health.$"

BattleTower_BattleRoom_Text_YouWillFace::
	.string "You will be facing opponent {STR_VAR_1}.\n"
	.string "Are you ready?$"

BattleTower_BattleRoom_Text_OfferSaveAndQuit::
	.string "Would you like to save and\n"
	.string "quit the game?$"

BattleTower_BattleRoom_Text_OfferCancel::
	.string "Would you like to cancel your Battle\n"
	.string "Room challenge?$"
