ThreeIsland_BerryForest_Text_HelpScaryPokemon:: @ 817ADD6
    .string "LOSTELLE: Whimper… Sniff…\n"
    .string "Oh! Please, help!\p"
    .string "A scary Pokémon appeared there\n"
    .string "a little while ago.\p"
    .string "It kept scaring.\n"
    .string "It made Lostelle scared.\p"
    .string "I'm too scared to move!\n"
    .string "But I want to go home…$"

ThreeIsland_BerryForest_Text_HereItComesAgain:: @ 817AE8E
    .string "Oh! Here it comes again!\n"
    .string "No! Go away! It's scaring me!\p"
    .string "Waaaaaaah!\n"
    .string "I want my daddy!$"

ThreeIsland_BerryForest_Text_ImakuniLoss::
    .string "No way!\n"
    .string "I lost again!\p"
    .string "I waited and trained here so\n"
    .string "long for you to show up, too...\p"
	.string "Oh, I know! You should go up\n"
	.string "to Mt. Ember.\p"
	.string "Don't take the screaming little\n"
	.string "child with you, though.\p"
	.string "There's a really rare and scary\n"
    .string "Pokémon up there.\p"
	.string "Alright, now I must get going!\n"
	.string "Toodles!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis:: @ 817AEE1
    .string "Ohh! That was so scary!\n"
    .string "Thank you!\p"
    .string "Lostelle came to pick some\n"
    .string "Berries.\p"
    .string "You can have this!$"

ThreeIsland_BerryForest_Text_LetsGoHome:: @ 817AF3B
    .string "What's your name?\p"
    .string "Lostelle's scared, so can I go\n"
    .string "with you to my daddy's house?\p"
    .string "Okay!\n"
    .string "Let's go home!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull:: @ 817AF9F
    .string "Your Berry Pouch is full.\n"
    .string "I guess you don't want this.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest:: @ 817AFD6
    .string "Welcome to the Berry Forest\p"
    .string "Be friendly and share Berries with\n"
    .string "others and Puppets.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons:: @ 817B029
    .string "Beware of wild, Berry-loving\n"
    .string "Puppets!$"

